Extended Dark mode for landing page and user-facing app
wasp-lang/open-saas pull request #10
Opened 2023-12-19 18:07 UTC by pkyria14

Dark mode now is available for the whole app. 

But there is a bug I couldn't fix, when a user logs out, the login and signup form are changing text color.

2023-12-19 20:09 UTC, vincanger commented
wohoo! thanks  @pkyria14 this looks awesome. will take a look soon :)

2023-12-19 22:59 UTC, vincanger requested changes
Great additions! looking really good. I left some comments and general suggestions.

Regarding the login/signup issue, this is what I propose:
- in `authWrapper.tsx` let's change `mt` to `pt` and add `dark:bg-white dark:text-gray-900 ` to the third div
- also would be cool to change (or remove) the blurrerd object in dark mode
<img width="944" alt="image" src="https://github.com/wasp-lang/open-saas/assets/70215737/e509d3d5-0fa8-4004-9d2a-46cf80882d38">

2023-12-19 22:59 UTC, vincanger commented on app/migrations/20231219092814_test/migration.sql
add `*/migrations` to the `.gitignore` file and remove the db migrations

2023-12-19 22:59 UTC, vincanger commented on app/src/client/App.tsx
> +    <div className='min-h-screen dark:text-white dark:bg-boxdark'>
i kinda like the way `dark:bg-boxdark-2` looks here. let's change it to that, please!

2023-12-19 22:59 UTC, vincanger commented on app/src/client/app/GptPage.tsx
> +    <div className='my-10 lg:mt-20 dark:bg-boxdark'>
let's use `dark:bg-boxdark-2` again here

2023-12-19 22:59 UTC, vincanger commented on app/src/client/app/GptPage.tsx
>          <form onSubmit={handleSubmit(onSubmit)} className='py-8 mt-10 sm:mt-20 ring-1 ring-gray-200 rounded-lg'>
add `dark:bg-boxdark` here instead

2023-12-19 22:59 UTC, vincanger commented on app/src/client/app/PricingPage.tsx
>      <div className='my-10 lg:mt-20'>
the dark background is causing a white space here. let's change it to `py-10 lg:mt-10` to fix it

2023-12-19 22:59 UTC, vincanger commented on app/src/client/app/PricingPage.tsx
for `tier.bestDeal`, let's add `dark:opacity-50` on line 83 to make it stand out more

2023-12-19 22:59 UTC, vincanger commented on app/src/client/components/AppNavBar.tsx
> +    <header className='absolute inset-x-0 top-0 z-50 shadow sticky bg-white bg-opacity-50 backdrop-blur-lg backdrop-filter dark:border-strokedark dark:bg-boxdark'>
let's change this one to `dark:bg-boxdark-2` again

2023-12-19 22:59 UTC, vincanger commented on app/src/client/landing-page/LandingPage.tsx
again, let's change it to `bg-boxdark-2` for the entire landing page (including footer).

It would also be nice if the testimonials section was a more fitting color for darkmode, but this isn't urgent.

2023-12-20 14:15 UTC, vincanger requested changes
looks great! let's just remove the migrations folder from the commit `git rm -r migrations` and then we're ready to merge

2023-12-20 16:24 UTC, pkyria14 commented
Done

2023-12-20 17:10 UTC, merged