Make the user entitiy user a uuid as its identifier
wasp-lang/open-saas pull request #189
Opened 2024-06-21 17:36 UTC by Reikon95

## Description

As discussed on Discord, change the default User entity ID to use a uuid instead of an int.

## Contributor Checklist

> Make sure to do the following steps if they are applicable to your PR:

- [ ] **Update e2e tests**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/template/e2e-tests](/template/e2e-tests) also.
- [ ] **Update demo app**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/opensaas-sh/app_diff](/opensaas-sh/app_diff) also. Check [/opensaas-sh/README.md](/opensaas-sh/README.md) for details.
- [ ] **Update docs**: If needed, update the [/opensaas-sh/blog/src/content/docs](/opensaas-sh/blog/src/content/docs).

2024-06-24 13:48 UTC, huextrat reviewed
https://github.com/wasp-lang/open-saas/blob/c3f9c8ae28d5823843119edf42eaa5c3805d668c/template/app/src/server/actions.ts#L289C14-L289C28

`updateUserById` should be updated to reflect the change from `number` to `string`

2024-06-26 12:15 UTC, vincanger commented
@Reikon95  we also need to update all the entity relations that reference the user.id, e.g.

```ts
entity GptResponse {=psl
  //...

  user                       User            @relation(fields: [userId], references: [id])
  userId                    String // <---- changed from Int to String
  ```

2024-06-26 12:19 UTC, vincanger commented
also @Reikon95 check out `const userInfo = context.user.id.toString();` in https://github.com/wasp-lang/open-saas/blob/c3f9c8ae28d5823843119edf42eaa5c3805d668c/template/app/src/server/actions.ts#L321

now that it's a UUID string, it probably won't throw an error, but it's best to remove this method

2024-06-26 12:19 UTC, vincanger requested changes
thanks for the PR, Cameron. Left a couple comments. Once those are addressed we can merge!

2024-06-26 17:09 UTC, Reikon95 commented
Thanks guys, have updated

2024-06-27 09:51 UTC, vincanger commented
Awesome @Reikon95 

merged!

2024-06-27 09:52 UTC, merged