rename TierIds to PaymentPlanIds
wasp-lang/open-saas pull request #200
Opened 2024-06-28 14:31 UTC by vincanger

addresses issue https://github.com/wasp-lang/open-saas/issues/199

2024-07-02 16:03 UTC, Martinsos requested changes
Left comments, nice improvements!
We will also want to add some info to the docs regarding the Stripe API version, right?

2024-07-02 16:03 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +    response.status(400).send('Webhook Error');
throw HttpError?

But actually, we don't know what happened here. So I would say it is best not to even try to catch this error, just let it go, it will be catched byy our default error middleware which will turn it into 500 error, which is probably right. So you can then remove this whole big try/catch block.

2024-07-03 08:47 UTC, vincanger commented on template/app/src/server/webhooks/stripe.ts
> +      const userStripeId = session.customer as string;
It's quite odd. The types in the Stripe SDK say that `session.customer` could be `string | StripeCustomer` but the description always says "the ID of the customer". So if I don't cast it as a string, I get an error when passing it to Prisma's UserDelegate.

2024-07-03 08:51 UTC, vincanger commented on template/app/src/server/webhooks/stripeUserPaymentDetails.ts
> +  if (args.subscriptionTier) data.subscriptionTier = args.subscriptionTier as string;
Otherwise the type checker throws an error when I pass it to prisma, because it says that `subscriptionTier` can't be of type `PaymentPlanId` and must be a string

2024-07-03 16:02 UTC, vincanger commented on template/app/src/server/webhooks/stripe.ts
>        const userStripeId = invoice.customer as string;
I took care of this now through a conditional check

2024-07-03 16:12 UTC, vincanger commented on template/app/src/server/webhooks/stripeUserPaymentDetails.ts
I went with `userStripePaymentDetails` because it is clear that we are affecting the users's stripe payment information, rather than `stripeUserPayment...` which may give the impression we're updating data on stripe's servers

2024-07-03 22:54 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +const getCustomerIdStringOrThrow = (userStripeId: unknown): string => {
One thing that is also weird here is that you take `unknown`, and also you just check if it exists and if it is string. You don't really get anything, you kind of validate it. In general, functions that take just one arg that can be nothing are weird functions -> why wansn't the case where that thing is nothing handled outside? Sometimes there is a reason for it, but sometimes they are a bit suspicious. So called "code smell".

I looked at calls below: you are either calling it on `subscription.customer` or `invoice.customer`. How about we modify it to be `async function getCustomerStripeIdOrThrow ({ customer?: unknown }) ...` -> but hm, again it is unknown and it might not exist. That is not great. Actually why it is unknown? We have `session = event.data.object as Stripe.Checkout.Session`. So how is it then that we don't know the type of `session.customer`, I would expect we know it? Or is that not the part of `Stripe.Checkout.Session` type?

@sodic do you have an opinion on this one, from the TypeScript side?

2024-07-03 22:54 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  const lineItemPriceId = line_items?.data[0]?.price?.id;
What if there are multiple line items, or if there are none? I think you handle the none case below, but you don't handle the case of multiple, you just ignore those. That is not terrible, but it might be nice to explicitly also throw an error in that case: we expected just one line item.

2024-07-03 22:54 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +    { userStripeId, subscriptionPlan: subscriptionPlan, numOfCreditsPurchased, datePaid: new Date() },
```suggestion
    { userStripeId, subscriptionPlan, numOfCreditsPurchased, datePaid: new Date() },
```

2024-07-03 22:54 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +    { userStripeId, subscriptionPlan: subscriptionPlan, numOfCreditsPurchased, datePaid: new Date() },
So you are updating datePaid in any case. Is that ok? We also want to update it if they went for subscription and not just credits? If so, ok!

2024-07-03 22:54 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +      break;
What if they add another payment plan, and they forget to add it here? I don't think we can easily catch that in compile time, but you can at least add default case here taht throws an error!

2024-07-03 22:54 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +      break;
Btw what we in general want is to have one place where developer declares a new payment plan and then TypeScript warns us with comipler errors about all the places in code where we also need to make some kind of change.
How could we achieve that it warns us we need to make a change here?

What we could do is say that every payment plan needs to also have a Stripe Price ID. Well, a method to obtain that at least. That method could then obtain if from env var. Then here we would just go through all the payment plans, call that method for each, and check if it matches line item, and decide which one is the correct one.
We could then also have another method that, for each payment plan, says how it affects subscription and how it affects credits, in the sense of which subscription does it create/start, and how much credits does it add. Then you would next call that method here, and that is it! This piece of code would then work automatically from here on.

To achieve this, we need a place where we have something like
```ts
type PaymentPlanId = 'hobby' | 'pro' | 'ten-credits';

function getPaymentPlanStripePriceId (planId: PaymentPlanId): string {
  switch ... that has process.env.'s in it
}

function getPaymentPlanSubscriptionId (planId: PaymentPlanId): string {
  switch ...
}

function getPaymentPlanCredits (planId: PaymentPlanId): number {
  switch ...
}
```

Notice that this even enables a single plan to both activate a subscription and also set some credits, which we might want or not want. If we sure we don't want this, we can instead reorganize things a bit here, probably by having `type SubscriptionPlanId = ...` and `type creditPlanId = ...` and then `type PaymentPlanId = SubscriptionPlanId | CreditPlanId`, what you actually already have, and then we have have more specific functions.

I might have gone a bit wrong here, for example maybe I forgot a bit about our situation with subscriptions and how they are stored in the database and stuff like t hat, so this design might need tweaking. Maybe central stuff should be `subscriptionPlans` and `creditPlans` and then this stuff built around it. But I think we should explore this kind of approach if possible.
Might be easiest if we go through this together, see if this is actually doable or I forgot about other parts of the codebase that make this not as straightforward. I think it is, I am just not sure about all the details yet.

2024-07-03 22:54 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  return await updateUserStripePaymentDetails({ userStripeId, datePaid: periodStart }, prismaUserDelegate);
```suggestion
  const datePaid = new Date(invoice.period_start * 1000);
  return await updateUserStripePaymentDetails({ userStripeId, datePaid }, prismaUserDelegate);
```

2024-07-03 22:54 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  if (subscription.cancel_at_period_end) subscriptionStatus = 'canceled';
This is a bit weird logic, could you explain it a bit?
You by default assume subscription is `active`. Why is that?
You check status only for `past_due`, why is that?
`cancel_at_period_end` -> we call that `cancel`. So the nomenclature on their and our side is not 100% the same. Do they have just `cancel` state also?

2024-07-03 22:54 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
You put these intro separate file -> not bad, although I probably would just keep tham in that origianl file, since they are to be used only there and nowhere else.

2024-07-03 22:54 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +      break;
I am also not yet 100% if we should go with `type PaymentPlanId` or `enum PaymentPlanId` hm. Maybe enum is better fit for this.

2024-07-04 09:19 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +      const userStripeId = session.customer as string;
Ha ok! But we are not sure - should we check then and throw an error if it is not a string?

2024-07-04 09:26 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +      break;
Ok one final thought: I know this is a bit of reverse on the split we did (from payment plans to subscriptions and credits), but it seems to me like the best option might be to go with `enum PaymentPlan { HOBBY, PRO, CREDITS_10 }`.

And, we assume that each plan can have certain effects: start a subscription, and/or add credits. Maybe combo of both starting subscription and adding credits is weird, but maybe it is not. One thing that I think is good here that this is very flexible, so they can model this as they like, we are not trying to overengineer.

Which means that we would then go with implementing functions like `getPlanSubscriptionId (plan: PaymentPlan): <hmstringortype?> { switch ... }` and `getPlanCredits` and `getPlanPrice` and so on, whatever we need, and it would all be defined in a single file! Yeah, I think this is the way to go!

2024-07-04 09:42 UTC, sodic reviewed
Answered some of the questions/dilemmas I was tagged on.

I might look at more stuff later :)

2024-07-04 09:42 UTC, sodic commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +      break;
### Enums

> ... Maybe enum is better fit for this.

I'll give you all the info I have and you can decide for yourself:
- Effective TypeScript (2nd edition), item 72
- https://github.com/wasp-lang/wasp/pull/1400#discussion_r1315502612
- https://github.com/wasp-lang/wasp/pull/1055#discussion_r1150698786 (

I would personally stick to the rule of thumb explained in the last comment: If you don't runtime type checking, stick with union types.

As for some of the other stuff...

### Enforcing Exhaustiveness
 > Btw what we in general want is to have one place where developer declares a new payment plan and then TypeScript warns us with comipler errors about all the places in code where we also need to make some kind of change.
 
Exactly, we should be forcing exhaustiveness, which means _"there must be a mapping defined for all values and the compiler should check for it."_

@Martinsos Tell me if I misunderstood your comment, but it doesn't seem to address this problem after identifying it at the beginning.

In any case, @vincanger, you should use (in this order of preference)
1. **A `Record`** - A `Record` means _"you're guaranteed to have a defined mapping for every possible key"_. This way, if someone adds a new `PaymentPlanId`, the compiler will ensure they update all the mappings. For more details, see _Effective TypeScript (2nd edition), Item 61_.
2. **Exhaustive switch statements** - You should prefer Records in almost all cases (they're simpler, first-class, and more declarative). Exhaustive switch statements are handy when you need to perform a side effect based on some value (but I don't see that being the case here).

### Naming
You should name values using PascalCase, not UPPERCASE:
```typescript
export enum SubscriptionPlanId {
  Hobby = 'hobby', // instead of "HOBBY"
  Pro = 'pro' // instead of "PRO"
}
```

### Linter
Many of the items mentioned in the comments can (and should) be caught by a linter.
@vincanger and @Martinsos, have you considered setting it up?

2024-07-04 09:42 UTC, sodic commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +const getCustomerIdStringOrThrow = (userStripeId: unknown): string => {
### Arrow functions
This is the original explanation: https://github.com/wasp-lang/wasp/issues/487

But I wrote it back when we were using JavaScript (there's an important caveat for TypeScript, also explained in _Effective TypeScript, Item 12_).

Anyway, I am no longer sure what to advocate. I like the "important stuff on top benefit", but perhaps I'd put more weight on consistency- You'll definitely have to use arrows _a lot_ (that's how our hooks and operations work), so you might as well use them all the time.

### `unknown` and validation
We should do validation as early as possible (i.e., when we receive the request). As soon as we ensure something has the type we expect it to have, we should stop validating the data and just rely on TypeScript.

The rule is: **Make sure something is of type `T` before you say it's of type `T`.** In other words, all validation should happen _before_ the assertion, not after it.

Therefore, this function shouldn't be doing the validation. The validation should be done before the `event.data.object as Stripe.Checkout.Session` expression:
1. **If receiving malformed data _is_ considered normal** (i.e., it's the user's direct input, Stripe can return the data in multiple formats, some customers don't have IDs...), we shouldn't raise an exception. We should instead parse the data and propagate the appropriate error to the user (using normal control flow).
2. **If receiving malformed _isn't_ considered normal** (i.e., Stripe accidentally broke its API), we should assert the data has the proper format and throw an exception otherwise. I assume this is the case here. To do such an assertion, you can either use a library (e.g., Zod), or write it [yourself](https://www.typescriptlang.org/play/?ssl=15&ssc=3&pln=1&pc=1#code/C4TwDgpgBAwgrgZ2AewLYQE5QLxQN4BQUxUAlgCYBcUSGpAdgOZEn0CG61tDjANC8TaMI1enFQAjTPwC+BAgDM49AMbBSyelAUAKMGxAAbZGypRlAa3rIA7vQCU+AVDYIEmYAEkE8JGkx6Bsam9s4A9GFQAG7IpIZsAITOKppIUCqIKOgYnuQ4UPpGJuQAdBQEcorKahparu4YXj6Z-hiBRabUltZ29tT1HggFQcVkQ75ZmE7EEQWYCsgYqOkAFhAqFkNs9HnAKxi2ZApQexAg2mxxFVBAA).

2024-07-04 09:52 UTC, sodic commented on template/app/src/client/app/AccountPage.tsx
> +                      {user.subscriptionPlan === SubscriptionPlanId.HOBBY ? 'Hobby' : 'Pro'} Plan
And use a `Record` please, not a switch (as per the other comment: https://github.com/wasp-lang/open-saas/pull/200#discussion_r1665442964) :)

Maybe you don't even need a function and it just becomes `prettyText[user.subscriptionPlan]` (although I would personally always abstract it under a function).

2024-07-04 09:54 UTC, sodic commented on template/app/src/client/app/PricingPage.tsx
> +  bestDeal?: boolean;
Seconded!

> This is the concept of defining state in such way that you can't have invalid combination of values.

Exactly, @vincanger take a look at _Effective TypeScript (2nd edition), item 29_ to get a better idea what this means specifically for TypeScript.

2024-07-04 10:01 UTC, sodic commented on template/app/src/client/app/PricingPage.tsx
> +                    {tier.id !== CreditsPlanId.TEN_CREDITS && '/month'}
> Another option could be to add this '/ month' value directlu to the PaymentPlan somewhere, maybe it could be part of price for example, so you just print that directly.

I wouldn't do this personally. Adding a `/month` to a business type feels too low-level and specific. How would we even call the field (price suffix perhaps, but I'm still not a fan).

> One solution is to add planType: 'subscription' | 'credits' to the PaymentPlan above.

I like this one, but my favorite option is defining a function `getPriceDisplay(plan: PaymentPlan): React.Component` and doing all the mapping inside.

**Note:** a better name is welcome, and I half-made up the `React.Component` type (perhaps there's something more appropriate).

2024-07-04 10:03 UTC, sodic commented on template/app/src/server/actions.ts
>    }
A `Record` please :)

See https://github.com/wasp-lang/open-saas/pull/200#discussion_r1665396829

2024-07-04 10:05 UTC, sodic commented on template/app/src/server/scripts/dbSeeds.ts
> +    subscriptionPlan: subscriptionStatus ? faker.helpers.arrayElement([SubscriptionPlanId.HOBBY, SubscriptionPlanId.PRO]) : null,
I got just the thing: https://github.com/wasp-lang/wasp/pull/961#discussion_r1086804020

2024-07-04 10:07 UTC, sodic commented on template/app/src/server/webhooks/stripe.ts
>      event = stripe.webhooks.constructEvent(request.body, sig, process.env.STRIPE_WEBHOOK_SECRET!);
Agree, we should check for null after the `try/catch` block and throw the appropriate error.

2024-07-04 10:08 UTC, sodic commented on template/app/src/server/webhooks/stripe.ts
> +    await handleCustomerSubscriptionDeleted(event, prismaUserDelegate);
I know you probably read it 3 times by now, but for completeness:

Use a Record: https://github.com/wasp-lang/open-saas/pull/200#discussion_r1665396829

2024-07-04 10:10 UTC, sodic commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  let session = event.data.object as Stripe.Checkout.Session;
Wrt to this: 
> you are assuming this will be Stripe.Checkout.Session. How do you know?

Check https://github.com/wasp-lang/open-saas/pull/200#discussion_r1665442964

The rest I agree with too :)

2024-07-04 10:13 UTC, sodic commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  if (subscription.cancel_at_period_end) subscriptionStatus = 'canceled';
Also, why mutate the `subscriptionStatus` instead of just defining a mapping with (you guessed it) a `Record`?

2024-07-04 10:14 UTC, sodic commented on template/app/src/server/webhooks/userStripePaymentDetails.ts
> +};
I don't know the domain that well, but something about this type seems like it's another candidate for what Martin talked about here: https://github.com/wasp-lang/open-saas/pull/200/files#r1664746512

I could be wrong though.

2024-07-04 10:19 UTC, sodic commented on template/app/src/server/webhooks/userStripePaymentDetails.ts
> +};
To fix this, check _Effective TypeScript (2nd edition), item 21_.

Also, we should find a better name for `data` and type it properly (without using `any`).

I'll help you out since it's a little weird (I'll assume the type of `data` is `Data`):
```typescript
const data: Data = {
  ...args.datePaid && { datePaid: args.datePaid },
  ...args.subscriptionPlan && { subscriptionPlan: args.subscriptionPlan },
  ...subscriptionStatus && { subscriptionStatus: args.subscriptionStatus },
  ...args.numberOfCreditsPurchased && { credits: { increment: args.numberOfCreditsPurchased } },
}
```

2024-07-04 10:31 UTC, sodic commented on template/app/src/shared/types.ts
> +export type PaymentPlanId = SubscriptionPlanId | CreditsPlanId;
I can't leave a comment on it because it's old code, but `SubscriptionStatusOption` has `null` in its union type. 

In general, each union type should strive to be a subtype of a primitive type (i.e., either all `number`s, all `string`s, all `object`s). Mixing them up makes the handling code more complicated.

So I recommend you change `null` to `'none'`.

2024-07-04 10:39 UTC, sodic commented on template/app/src/shared/constants.ts
I advise removing this file.

Each file should carry a semantic name and be relevant because of what it does (not because it contains a certain kind of symbol, e.g., constants).

You wouldn't call a file "functions" or "variables" ... So why are "constants" any different?

The same thing applies to the `types` file (you wouldn't call a file `values`, so why `types`).

In all these cases, we should split the files in such a way that the symbols inside have some kind of semantic meaning, and then name the file after that meaning (e.g., payment.ts).

2024-07-04 10:40 UTC, sodic commented on template/app/src/shared/constants.ts
>  export const DOCS_URL = 'https://docs.opensaas.sh';
This should also be `PascalCase`, it's the standard naming convention.

2024-07-04 11:05 UTC, Martinsos commented on template/app/src/server/scripts/dbSeeds.ts
> +    subscriptionPlan: subscriptionStatus ? faker.helpers.arrayElement([SubscriptionPlanId.HOBBY, SubscriptionPlanId.PRO]) : null,
So Object.values? I read that works only on enums with string values though, so gotta be careful -> but it should work in our case then.

2024-07-04 11:21 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +      break;
Linter -> sure!

union type vs enum -> I read they are quite similar but enum is kind of opaque regarding actual value so that can be nice. I think both would work okish here, not yet sure till we try it (I am not sure how much we need it in value space, I think we might). Leanign toward enum at the moment.

As for the rest -> Record is cool! I love that you gave us links to read. It would however also be super helpful if you wrote in a very direct and practical manner what you imagined here. Are you aiming for something like this:

```ts
enum PaymentPlan {
  Hobby = "Hobby",
  Pro = "Pro",
  Credits10 = "Credits10"
};

interface PaymentPlanImpl {
  subscriptionId?: string;
  credits?: number;
  getStripePriceId: (): string;
};

const paymentPlans: Record<PaymentPlan, PaymentPlanImpl> = {
  PaymentPlan.Hobby: {
    subscriptionId: "something",
    getStripePriceId: () => { return process.env.... }
  },
  PaymentPlan.Pro: ...,
  Credits10: ...,
}
```

2024-07-04 11:32 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +      break;
Or we could also do a Record per a method / thing?

```ts
function getPaymentPlanSubscriptionId (plan: PaymentPlan) {
  return ({
    Hobby: 'foo',
    Pro: 'bar',
    Credits10: 'buzz'
  } satisfies Record<PaymentPlan, string>)[plan];
}
```

What do you think is better / more idiomatic?

2024-07-04 11:37 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  if (subscription.cancel_at_period_end) subscriptionStatus = 'canceled';
@sodic could you maybe provide a quick exmaple how you would use `Record` here?

2024-07-04 11:42 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +const getCustomerIdStringOrThrow = (userStripeId: unknown): string => {
@sodic regarding not raising an exception if malformed data is considered normal, but propagating appropriate error tot he user using normal control flow. How do you imagine that in practice? In which situation is malformed data considered normal? Also, I would say here raising exception is actually a normal control flow for us -> because it is an HttpException, and those are handled by global server middleware and returned as a response. So normal control flow can actually be raising an exception!

2024-07-04 11:44 UTC, Martinsos commented on template/app/src/server/webhooks/userStripePaymentDetails.ts
> +};
@sodic I was considering this, but was wondering if it indeed is a better solution. Maybe I have to read that item 21 which I don't ahve time for now, but I gave up on this different approach as it didn't seem to improve anything, and some people might say it is more convoluted even (I hit such resistance in the past in our PRs when I tried to do this).

2024-07-04 11:45 UTC, Martinsos commented on template/app/src/shared/constants.ts
We will be vertically organizing this code, but later, so I didn't want to advise this yet. I would say let's leave this as it is in this PR, to get stuff working, and then we will reorganize all of this anyway quite soon.

2024-07-04 12:02 UTC, sodic reviewed
I left some comments and links to material that should make them clearer, but you might have trouble figuring out some of my suggestions.

If that happens, call me up and I'll elaborate (or we can even jump on a call).

2024-07-04 12:03 UTC, sodic commented on template/app/src/shared/constants.ts
I'm guessing you meant to say "I couldn't agree more" :smile: 

Ok, fair enough, let's keep it.

2024-07-04 12:07 UTC, sodic commented on template/app/src/server/webhooks/userStripePaymentDetails.ts
> +};
Yes, I'm fairly confident that you'll agree with this approach once you read Item 21, so I suggest we follow it.

The benefits will become more apparent when `data` gets a proper type.

2024-07-04 12:37 UTC, Martinsos commented on template/app/src/shared/constants.ts
actually vince you decide i might be too cautious here

2024-07-04 12:43 UTC, sodic commented on template/app/src/server/scripts/dbSeeds.ts
> +    subscriptionPlan: subscriptionStatus ? faker.helpers.arrayElement([SubscriptionPlanId.HOBBY, SubscriptionPlanId.PRO]) : null,
That's true, but we shouldn't be using enums with non-string values anyway - they're very very weird.

2024-07-04 12:45 UTC, sodic commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +const getCustomerIdStringOrThrow = (userStripeId: unknown): string => {
>  How do you imagine that in practice? In which situation is malformed data considered normal? 

Unless someone is really curious, I won't go into it now since it's not relevant to this case.

2024-07-04 13:06 UTC, sodic commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  if (subscription.cancel_at_period_end) subscriptionStatus = 'canceled';
My bad, I thought we were making all the decisions based on `subscription.status`. I know see that's not the case. No place for a record here.

On a related note, though: we should change the name of `SubscriptionStatusOptions`. Another comment talks about that: https://github.com/wasp-lang/open-saas/pull/200/files/3c17bdba4d8a3aafd42a231d352a8af969b6f2d1#r1665506364

2024-07-04 14:11 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +      break;
ok nice! aha satisfies would allow for extra fields, forgot that. makes all sense to me!
what about one funtion that returns whole implementation vs multiple functions? i guess both work but multiple functions sounds a bit better to me, a bit simpler in a good way.

2024-07-04 14:16 UTC, sodic commented on template/app/src/server/webhooks/stripe.ts
> +    await handleCustomerSubscriptionDeleted(event, prismaUserDelegate);
To do it here, we need to go through a couple of steps:
1. Decide which Stripe events we expect
2. Come up with a uniform interface for handling those Stripe events.
3. Filter out unexpected Stripe events.
4. Create a handler mapping for expected Stripe events.

## Step 1: Decide which events we expect
Judging by the current code, we want to handle:
- `"checkout.session.completed"`
- `"invoice.paid"`
- `"customer.subscription.updated"`
- `"customer.subscription.deleted"`

So let's design a system for those. We can start by defining an enum listing all the expected events:
```typescript
enum StripeEventType {
  CheckoutCompleted = "checkout.session.completed",
  InvoicePaid = "invoice.paid",
  SubscriptionUpdated = "customer.subscription.updated",
  SubscriptionDeleted = "customer.subscription.deleted",
}
```

## Step 2: Uniform interface for event handlers
You have 4 event handlers:
 - `handleCheckoutSessionCompleted`
 - `handleInvoicePaid`
 - `handleCustomerSubscriptionUpdated`
 - `handleCustomerSubscriptionDeleted`

Some of them return a `Promise<user>`, others return `Promise<void>`. But the returned `user` objects are never used, so why not make them all return `void`?

After changing all handler implementations to return `void`, we should follow Item 12 from Effective TypeScript and do the following:
```typescript
export type StripeEventHandler =
  (event: Stripe.Event, prismaUserDelegate: PrismaUserDelegate) => Promise<void>

export const handleCheckoutSessionCompleted: StripeEventHandler =  
  async (event, prismaUserDelegate) => { ... }

export const handleInvoicePaid: StripeEventHandler = 
  async (event, prismaUserDelegate) => { ... }

export const handleCustomerSubscriptionUpdated: StripeEventHandler =
  async (event, prismaUserDelegate) => { ... }

export const handleCustomerSubscriptionDeleted: StripeEventHandler = 
  async (event, prismaUserDelegate) => { ... }
```
P.S. You should always annotate return types for module boundaries instead of leaving them to type inference. More info here: https://github.com/wasp-lang/vscode-wasp/pull/6#discussion_r970774084

## Step 3: Filtering out unexpected Stripe events
Before mapping expected events to their appropriate handlers, we'll have to filter out unexpected events (and throw an appropriate error).

We can do that with a type guard:
```typescript
function isStripeEventExpected(event: Stripe.Event): event is Stripe.Event & { type: StripeEventType } {
  return Object.values(StripeEventType).includes(event.type as StripeEventType)
}
```
This way, if the event isn't something we expect, we can immediately throw an exception:
```typescript
if (!isStripeEventExpected(event)) {
  // handle invalid event
  throw new Error('...')
}
```
## Step 4: Mapping expected Stripe events to appropriate handlers
Once we make sure we're only dealing with events we know how to handle, it's time to define a mapping between events and their handlers:
```typescript
function getHandlerForStripeEvent(event: StripeEventType) {
  const eventHandlers: Record<StripeEventType, StripeEventHandler> = {
    [StripeEventType.CheckoutCompleted]: handleCheckoutSessionCompleted,
    [StripeEventType.InvoicePaid]: handleInvoicePaid,
    [StripeEventType.SubscriptionUpdated]: handleCustomerSubscriptionUpdated,
    [StripeEventType.SubscriptionDeleted]: handleCustomerSubscriptionDeleted,
  }
  return eventHandlers[event];
}
```
The `Record<StripeEventType, StripeEventHandler>` tells the compiler "ensure this object defines a mapping for every possible `StripeEventType`.
In other words, when someone adds a new event type to the `enum`, the compiler will ensure they remember to add a handler for it.

## Bringing it all together
Assuming we implement everything described above, this is how the `stripeWebhook` function looks like:
```typescript
export const stripeWebhook: StripeWebhook = async (request, response, context) => {
  const sig = request.headers['stripe-signature'];
  if (!sig) {
    throw new HttpError(400, 'Stripe Webhook Signature Not Provided');
  }

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(request.body, sig, process.env.STRIPE_WEBHOOK_SECRET!);
  } catch (err) {
    throw new HttpError(400, 'Error Constructing Stripe Webhook Event');
  }

  if (!isStripeEventExpected(event)) {
    throw new Error('...')
  }

  const handleEvent = getHandlerForStripeEvent(event.type)
  await handleEvent(event, context.entities.User);

  response.json({ received: true }); // Stripe expects a 200 response to acknowledge receipt of the webhook
};
```

Why is this better:
 - We check for unknown events and throw appropriate errors if they occur.
 - We have no chance of adding a new event and forgetting to define a handler for it (the compiler has your back).

2024-07-04 14:48 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +    await handleCustomerSubscriptionDeleted(event, prismaUserDelegate);
@sodic , one thing to keep in mind here is that since OpenSaas is template, users of it are going to be reading and using this code, so sometimes it might be worth it going for a bit simpler option even if we loose a bit of type safety just for the sake of keeping things simpler / approachable.

With that in regard, I wonder if I am missing something, but it seems to me like we have to do quite some stuff here but don't gain much?
We could have a switch statement that on default throw an error that event is unknown, and that is it! Much simpler than what you suggested here, but seems equally good to me? There is just one place where we handle / define these events and it is right here (maybe that is what you didn't know?), so adding a new event and forgetting to add a handler is more or less impossible, how could that happen? Sure, you could leave the whole case empty by accident, but you could also by accident define an empty function for handling the event.

Let me know if I am missing something hm.

Btw this is what switch statement would look like, just to be super clear:
```ts
switch (event.type === 'checkout.session.completed') {
  case 'checkout.session.completed':
    await handleCheckoutSessionCompleted(event, prismaUserDelegate);
    break;
  case 'invoice.paid':
    await handleInvoicePaid(event, prismaUserDelegate);
    break;
  case 'customer.subscription.updated':
    await handleCustomerSubscriptionUpdated(event, prismaUserDelegate);
    break;
  case 'customer.subscription.deleted':
    await handleCustomerSubscriptionDeleted(event, prismaUserDelegate);
    break;
  default:
    throw new HttpError(400, `Unexpected Stripe webhook event type: ${event.type}`);
```
To me this seems super local, super tight, super simple, not much/any space here for some mistakes in the style of "I added something somewhere and forgot to do something here" or vice versa.

2024-07-04 15:07 UTC, vincanger commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  if (subscription.cancel_at_period_end) subscriptionStatus = 'canceled';
hmm I tried the Record way, but I found returning the function and then having to call it a bit awkward, so I went with switch

```ts
  switch (event.type as StripeEventTypes) {
    case 'checkout.session.completed':
      await handleCheckoutSessionCompleted(event, prismaUserDelegate);
    case 'invoice.paid':
      await handleInvoicePaid(event, prismaUserDelegate);
    case 'customer.subscription.updated':
      await handleCustomerSubscriptionUpdated(event, prismaUserDelegate);
    case 'customer.subscription.deleted':
      await handleCustomerSubscriptionDeleted(event, prismaUserDelegate);
    default:
      console.log('Unhandled event type: ', event.type);
  }
  ```

2024-07-04 15:13 UTC, vincanger commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +      break;
I went with a dual approach in the end, as there are some cases where I still want to differentiate between a `subscriptionPlan` and have the appropriate enum for it (without Credit plans in there):

```ts
export enum PaymentPlanId {
  SubscriptionHobby = SubscriptionPlanId.Hobby,
  SubscriptionPro = SubscriptionPlanId.Pro,
  Credits10 = CreditsPlanId.Credits10,
  // Credits20 = CreditsPlanId.Credits20
}
```

2024-07-04 15:21 UTC, vincanger commented on template/app/src/server/webhooks/stripe.ts
> +    await handleCustomerSubscriptionDeleted(event, prismaUserDelegate);
yeah I agree with martin here 
hmm I tried the Record way, but I didn't really see the benefit of the record here. plus returning the event handler function and then having to call it a bit awkward, so I went with switch:

```ts
  switch (event.type as StripeEventTypes) {
    case 'checkout.session.completed':
      await handleCheckoutSessionCompleted(event, prismaUserDelegate);
    case 'invoice.paid':
      await handleInvoicePaid(event, prismaUserDelegate);
    case 'customer.subscription.updated':
      await handleCustomerSubscriptionUpdated(event, prismaUserDelegate);
    case 'customer.subscription.deleted':
      await handleCustomerSubscriptionDeleted(event, prismaUserDelegate);
    default:
      console.log('Unhandled event type: ', event.type);
  }
  ```
  
  instead of:
  
  ```ts
    const eventTypeHandlers: Record<StripeEvents, () => Promise<User>> = {
    'checkout.session.completed': () => handleCheckoutSessionCompleted(event, prismaUserDelegate),
    'invoice.paid': () => handleInvoicePaid(event, prismaUserDelegate),
    'customer.subscription.updated': () => handleCustomerSubscriptionUpdated(event, prismaUserDelegate),
    'customer.subscription.deleted': () => handleCustomerSubscriptionDeleted(event, prismaUserDelegate),
  };
  const eventHandler = eventTypeHandlers[event.type as StripeEvents];
  if (!eventHandler) {
   console.log('Unhandled event type: ', event.type)
  } else {
    await eventHandler();
  }
  ```

2024-07-04 15:26 UTC, vincanger commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +const getCustomerIdStringOrThrow = (userStripeId: unknown): string => {
So the type provided by Stripe in this case is 

```ts
Stripe.Checkout.Session.customer: string | Stripe.Customer | Stripe.DeletedCustomer | null
```

In this case, I think it's best to check if it exists first, if not throw an error, then validate it with the function. That's what I went ahead and did for now...

2024-07-04 15:43 UTC, sodic commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +const getCustomerIdStringOrThrow = (userStripeId: unknown): string => {
Hmm, @vincanger is this comment in the wrong thread maybe :thinking:

2024-07-04 15:45 UTC, sodic commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  if (subscription.cancel_at_period_end) subscriptionStatus = 'canceled';
@vincanger Is GitHub acting out? This comment seems to be a duplicate from a different thread and not related to this one?

2024-07-04 15:55 UTC, sodic commented
@vincanger Pro tip:

When you want to link a pull request to an issue, use [GitHub's special words](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests).

This way, once you merge the PR, the issue automatically gets closed.

In this case, you can edit your description to say "Closes #199" or "Fixes #199" instead of "addresses issue #199".

You'll see how GitHub immediately underlines it and add the PR under the issue's title

2024-07-04 15:59 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +    await handleCustomerSubscriptionDeleted(event, prismaUserDelegate);
@sodic but the only place where we do add events is this very switch statement, so you can't really add is somewhere and not have it here -> this is exactly where we are adding them! I think you are missing context and situation is actually simpler than what you assumed -> these events are handleda and defined here and nowehere else, and that is not likely to change.
Ok switch it is then in this case, nice! Still was cool to see the other way.

2024-07-04 16:02 UTC, sodic commented on template/app/src/server/webhooks/stripe.ts
> +    await handleCustomerSubscriptionDeleted(event, prismaUserDelegate);
Ahh, you're right. My explanation is assuming there's an enum listing the events.

But yeah, no enum no problem.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +  const prettyPrintSubscriptionPlan = (userSubscriptionPlan: User['subscriptionPlan']) => {
It is nice that you have these functions! But, it is also a bit hard to get to what `UserCurrentSubscriptionStatus` is actually doing because I need to read all these helper functions first to get to it.

I would advise taking them all out, and also giving them return types.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +      return capitalizeFirstLetter(SubscriptionPlanId.Hobby);
Why did you decide to go with capitalizing first letter, instead of just directly providing string? Why not direclty just return `Hobby`? That way you don't have to rely on the value of `SubscriptionPlanId.Hobby` being  what you think it is -> you certainly assume it has some reasonable value. What if its value was `hobby-plan-v1` or something? So if we can skip that assumption + get rid of that helper function for capitlaizng first letter, that sounds good to me.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +      return capitalizeFirstLetter(SubscriptionPlanId.Hobby);
Copy/paste typo:
```suggestion
      return capitalizeFirstLetter(SubscriptionPlanId.Pro);
```

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +    }
What if we didn't match any of these two plans? We should throw an error! Maybe we were given some silly value?

Also, we have the switch/record situation here -> if new subscription plan is added, we won't detect here that we are missing implementation for it. So we shoudl use Record approach here.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +  const prettyPrintSubscriptionPlan = (userSubscriptionPlan: User['subscriptionPlan']) => {
Also, the fact taht we take `User['subscriptionPlan']` as an arugment is a bit weird. Why not `SubscriptionPlanId`? I am not sure, maybe as a helper function this makes sense, but it is a bit suspicious.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +    if (!date) {
But wait you said it can be null, and then you throw an error if it is null! Isn't that unusual? Actually you don't throw an error, you print error to the console and then return '.'. Quite peculiar behaviour! Suspicious.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +  function getSubscriptionMessage(subscriptionStatus: User['subscriptionStatus']) {
```suggestion
  function getDescriptionOfSubscriptionStatus(subscriptionStatus: User['subscriptionStatus']) {
```

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +    const plan = prettyPrintSubscriptionPlan(user.subscriptionPlan);
```suggestion
    const planName = prettyPrintSubscriptionPlan(user.subscriptionPlan);
```

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +      case 'active' satisfies SubscriptionStatusOptions:
What is the thing with all the `satisfies` here?

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +    // TODO: refactor this as a Record<SubscriptionStatusOptions, string> instead of a switch statement?
Yeah, I think that would be better!

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +  function getSubscriptionMessage(subscriptionStatus: User['subscriptionStatus']) {
Should we make input arguemnt be `SubscriptionStatusOptions`?

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +  return (
Hm so you are not printing just subscription status, but also info about credits if no subscirpitono. Sounds like you are printing status of their payment plan. So maybe let's rename the component?

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/PricingPage.tsx
> +  mode: 'subscription' | 'payment';
A bit weird that payment plan can be subscirption or payment. Now we are using term Payments in two ways which is tricky. I liked "credits" better then. Or if not "credits", can we find something else that is not "payment"?

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/PricingPage.tsx
> +export const paymentPlanArr: PaymentPlan[] = [
```suggestion
export const paymentPlans: PaymentPlan[] = [
```

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/PricingPage.tsx
> +                    {plan.mode === 'subscription' && '/month'}
What I don't like still is that this `/month` is here. It is weird. It is not just visualization, it is a vital piece of information. I would stuff it into `price`, make it part of that string, not have it here. OR, rename `price` to `pricePerMonth` -> yes, if you do that, then it is ok. Because now information about month is there, and this is just visualization of it.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/PricingPage.tsx
> +type PaymentPlan = {
This whole type definition: it feels like it should be moved somehwere else, more "central", and not here in a React compnoent that is merely worried with the visualization of payment plans. We can postpone that for later potentially, not to overcomplicate this PR, but it will need doing at some point. At least some of this information should probalby be moved.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/server/stripe/paymentPlans.ts
> +  mode: 'subscription' | 'payment'
This is tricky, you can have `credits` set to a value but also `mode` set to `subscription`. You are allowing invalid combinations. We should avoid that.

Also, we are duplicating information about which payment is in which mode, because you define it here, but you also defined it in that React component. One can update one side of it and forget the other and vice versa.

We need to centralize this stuff. Yeah, let's do it now, now is the moment.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/server/stripe/paymentPlans.ts
> +  stripePriceID: string | undefined;
How is it that stripePriceId can be undefined? I would expect every plan must have this?

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/server/stripe/paymentPlans.ts
> +  // TODO: check if ENV VARS are set in the .env file
Ok yeah let's check that!

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/server/actions.ts
> +  if (!priceId || !mode) {
This is a bit weird, I would kind of expect priceId and mode to be truthy / defined, since all the types match, so I wouldn't expect we have to do this check here.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/server/actions.ts
> +  if (!customer) {
I would kind of expect `fetchStripeCustomer` to throw this. Not 100% sure though, depends on situation.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/server/actions.ts
> +  if (!session) {
I would kind of expect `createStripeCheckoutSession` to throw this. Not 100% sure though, depends on situation.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +type StripeEventTypes =
Do we need this?

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +      console.log('Unhandled event type: ', event.type);
Let's do `console.error`? And maybe also add to their text that a bit of instructions, that they might want to listen to that event type? Or is this all too much? You know more about webhooks so I am not sure what is best here actually.

2024-07-04 21:00 UTC, Martinsos commented on template/app/src/client/app/PricingPage.tsx
> +                    {tier.id !== CreditsPlanId.TEN_CREDITS && '/month'}
@vincanger resolve this one when done with it.

2024-07-04 21:07 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  const statusMapping: Record<string, SubscriptionStatusOptions> = {
I am not sure you get much here using Record sicne first key is `string`, so it won't enforce in any way that all keys are used. So let's use something simpler? Also, it is not really doing anything hm, it just maps same values to same values?

2024-07-04 21:07 UTC, Martinsos commented on template/app/src/shared/constants.ts
Actually, I converted. Looking at other files, we do need a strong central place that defines central PaymentPlan logic, that is relevant both for client and server. Right now it is too scattered and that is causing issues.
Let's name it `paymentPlan.ts` or something like that.

2024-07-04 21:08 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +    await handleCustomerSubscriptionDeleted(event, prismaUserDelegate);
@vincanger resolve this one when you are happy with it!

2024-07-04 21:09 UTC, Martinsos commented on template/app/src/server/webhooks/stripeEventHandlers.ts
> +  const lineItemPriceId = line_items?.data[0]?.price?.id;
@vincanger resolve at will

2024-07-05 00:33 UTC, Martinsos commented
@sodic @vincanger I wanted to try out myself some things I was suggesting (mostly regarding consolidating types), so that I don't suggest stuff that is not doable or won't look good once it is done, and I got pulled in and ended up implementing stuff.

First I ended up with this PR: https://github.com/wasp-lang/open-saas/pull/217, and then I, on top of that one, made a bit different attempt with this one: https://github.com/wasp-lang/open-saas/pull/218 . I am not sure which one I prefer, maybe the first one, but it is tight: both are a bit clunky in some aspects, but also both work quite well I think.

Please take a look and see if there is anything useful you can use.

Also, since I will be traveling in the following days, and @sodic already got quite involved, I suggest @sodic that you take over the reviewing of this PR and drive it to the end with @vincanger . I think I covered all I could from my side, and you will be able to contribute some extra knowledge on the TS side.

2024-07-05 08:51 UTC, vincanger commented on template/app/src/client/app/PricingPage.tsx
> +                    {tier.id !== CreditsPlanId.TEN_CREDITS && '/month'}
> @vincanger resolve this one when done with it.

I did already, by adding a `mode` property (this is what stripe calls it, too):

```ts
{plan.mode === 'subscription' && '/month'}
```

2024-07-06 07:30 UTC, vincanger reviewed
Thanks for all your comments and help here @sodic @Martinsos -- this was a chunky boy!

There was a lot of new insight here for me, so it took me a while to get a grasp of everything.

I merged Martin's ideas from PR https://github.com/wasp-lang/open-saas/pull/217 for consolidating types. I _think_ we're close to being done here.

I also added docs on stripe api/client versioning. The only thing left to do is create the new `app_diff` but I think I will do this in a new PR at another time because of there have been so many big changes and I don't want to rush it.

2024-07-08 11:42 UTC, vincanger commented on template/app/src/shared/types.ts
> +export type PaymentPlanId = SubscriptionPlanId | CreditsPlanId;
Nice.

In the end I just removed `null` because `user.subscriptionStatus` is an optional property in the prisma schema, so `null` was redundant in this case.

2024-07-08 16:32 UTC, Martinsos commented on template/app/src/client/app/PricingPage.tsx
> +  mode: 'subscription' | 'payment';
I the #217 , what I did is used "credits" and "subscription" on our side, and then there is a piece of logic that transforms that into "subscription" and "payment": did we go with that at the end? We will be using other providers anyway, so it is proobably best if we have our nomenclature on our side, and then we transform it to theirs.

2024-07-08 19:58 UTC, Martinsos reviewed
@vincanger left some extra comments.
Pls go through the "conversation" tab in Github and resolve all the comments that are still open but can be resolved!

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +  return statusToMessage[subscriptionStatus as SubscriptionStatus];
Feels like this `as` should not be here, instead you should take SubscriptionStatus as an argument to a function instead of a stirng, and then teh caller should bother with ensuring it has actual SubscriptionStatus.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/client/app/PricingPage.tsx
>      name: 'Hobby',
I am wondering, you now have that function that returns a pretty name given an id of a payment plan, why not use that to obtain the pretty name here? Or are these these two not the same semantically?

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/client/landing-page/urls.ts
Hah better but a bit unusual :D! `landing-page/urls`. "urls" is very generic but correct. Landing-page is a bit specific, but it works. I would be tempted to take it a level or two higher, and have it in `src/urls.ts`. Or `src/common.ts`. That is very generic though. Maybe `src/external-urls.ts` hm. Since it is not in any way client specific. That said, do it as you think is best, even if that is leaving it as it is now.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/gpt/schedule.ts
Oho nice stuff! Let's not get too much into it in this PR, but it looks good to see stuff moving in better directions.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/payment/plans.ts
> +// TODO: Move to some server/utils.js?
Don't forget about this one.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/payment/plans.ts
> +export function parsePaymentPlanId(planId: string): PaymentPlanId {
You might need something similar for SubscriptionStatus, to get rid of those `as SubscriptionStatus`.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/server/actions.ts
> +export const stripePayment: StripePayment<PaymentPlanId, StripePaymentResult> = async (paymentPlanId, context) => {
What does this function do, perform payment on Stripe? Right now it is a noun which is weird for a function. So I would consider renaming it to `performStripePayment` or `activatePlanOnStripe` or whatever you think is the best name for it. It might help if you can write in a verbose sentence or two what this function exactly does. Hm does it actually perform payment? Or it just creates this checkout session thing? What does that mean actually? Yeah, good name here would help.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +  const secret = process.env.STRIPE_WEBHOOK_SECRET;
You might want to use the new fuction we have for requireing an env var (it is in payment/plans right now, but if you extract is as the TODO above it suggested, then you can use it here. And any error thrown that is not an HttpError will by dfeault get converted to Http 500 error in Wasp, so you can just call it as it is and taht is it, no additional error handling is needed.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +      console.error('Unhandled event type: ', event.type);
Aha, in development it is fine if we receive events that we are not handling? What about production? If that is also fine in production, then we shouldn't have `console.error` here, because it is not an error. Maybe `console.log`, or maybe not even that.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +  switch (subscription.status as Stripe.Subscription.Status) {
weird that yo have to type this. `subscription` is of `Stripe.Subscription` type, so how is `subscription.status` not of `Stripe.Subscription.Status`? If that is so no worries, just a bit surprised!

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +      break;
I would consider putting a default here that results in runtime error. I know it should not happen, but you used `as` above which means you are vouching for that type to be correct, which means we can't be sure really, so better have things fail here if that happens then continuting and doing who knows what. Aha I see now that you have a line below that handles it! Hm ok. A bit confusing but works, might be fine.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +function validateAndUseLineItemData(line_items: Stripe.ApiList<Stripe.LineItem> | undefined) {
Name of this function is general. But it does something more specific. It cares about obtaining a single line item, and even complains if there are more. That is good, we need that, but name doesn't make that clear. I would make that clear in the name. Also I would consider moving this function to be inside of the function that uses it since it is so specific for it, but you don't have to do that.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/server/webhooks/stripe.ts
> +function validateUserStripeIdOrThrow(userStripeId: Stripe.Checkout.Session['customer']) {
This function is missing a return type.

2024-07-08 19:58 UTC, Martinsos commented on template/app/src/server/webhooks/stripePaymentDetails.ts
> +export type PrismaUserDelegate = Parameters<StripeWebhook>[2]['entities']['User'];
This feels a bit unusual, fragile. Can't we get the type of PrismaUserDelegate in some more direct way? Where is this type used that we need to export it from here? @sodic what do you think?

2024-07-09 13:37 UTC, infomiho approved these changes

2024-07-09 14:59 UTC, vincanger commented on template/app/src/client/app/AccountPage.tsx
> +function UserCurrentPaymentPlan({ subscriptionPlan, subscriptionStatus, datePaid, credits }: Pick<User, 'subscriptionPlan' | 'subscriptionStatus' | 'datePaid' | 'credits'>) {
numbers in curly braces in JSX will get rendered as strings.

datePaid is a Date type but we parse it to a string with `.toLocaleDateString` in one of the prettyPrintDate functions

2024-07-09 17:32 UTC, vincanger commented on template/app/src/server/webhooks/stripe.ts
> +      console.error('Unhandled event type: ', event.type);
No, I double checked and you will only be sent events that you selected/programmed when creating your production webhook

2024-07-09 17:34 UTC, vincanger commented on template/app/src/server/webhooks/stripe.ts
> +  switch (subscription.status as Stripe.Subscription.Status) {
you're right. it wasn't necessary. must have been a leftover

2024-07-09 17:42 UTC, Martinsos commented on template/app/src/client/app/AccountPage.tsx
> +function UserCurrentPaymentPlan({ subscriptionPlan, subscriptionStatus, datePaid, credits }: Pick<User, 'subscriptionPlan' | 'subscriptionStatus' | 'datePaid' | 'credits'>) {
Ok so credits and datePaid work -> but it is still tricky because you are assuming these to be something that is renderable by React, and types are not reflecting that. I would either make them quite strict in the sense that they are `string` or `number` or `Date`, stuff you know will work for you, or if there is a type like `ReactRenderable` by React maybe, you can use that. But that is all better than assuming type is whatever User has on it.
It is quite peculiar that TS has this feature of defining type on another type like this -> but that is to be used so easily I would say, or you can have types doing the wrong thing. You want such types that you know, once you get those values, that you can use them as you want without any issues / runtime errors (well, as much as possible taking into account that not everything can be captured in the type system).

2024-07-09 17:46 UTC, Martinsos commented on template/app/src/server/actions.ts
> +export const stripePayment: StripePayment<PaymentPlanId, StripePaymentResult> = async (paymentPlanId, context) => {
@vincanger you didn't yet push this change right?

2024-07-09 17:48 UTC, vincanger commented on template/app/src/server/webhooks/stripe.ts
> +      break;
good catch. We should actually do nothing if `subscriptionStatus === undefined` because there are certain status updates, like `trailing`, that we are not configuring in our Stripe product, therefore there's no need to handle this status event.

2024-07-09 17:53 UTC, vincanger commented on template/app/src/server/webhooks/stripePaymentDetails.ts
> +export type PrismaUserDelegate = Parameters<StripeWebhook>[2]['entities']['User'];
We tried that but we weren't getting proper types on the `update` method any other way. This type gave us the best results, and correctly warns us if the data we're passing when calling `userDelegate.update` was not of the correct type.

2024-07-10 09:47 UTC, Martinsos approved these changes
Nice, we got it all in a good shape!

2024-07-10 11:08 UTC, vincanger commented
> Nice, we got it all in a good shape!

updated docs and app_diff as well

2024-07-10 14:08 UTC, merged