Break up LandingPage components into sub-components
wasp-lang/open-saas pull request #214
Opened 2024-07-03 09:04 UTC by surendra-manjhi

## Description

This PR fixes Break up LandingPage.tsx components into multiple sub-components issue.
Fixes: #147

## Contributor Checklist

> Make sure to do the following steps if they are applicable to your PR:

- [ ] **Update e2e tests**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/template/e2e-tests](/template/e2e-tests) also.
- [ ] **Update demo app**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/opensaas-sh/app_diff](/opensaas-sh/app_diff) also. Check [/opensaas-sh/README.md](/opensaas-sh/README.md) for details.
- [ ] **Update docs**: If needed, update the [/opensaas-sh/blog/src/content/docs](/opensaas-sh/blog/src/content/docs).

2024-07-09 09:12 UTC, Martinsos requested changes
Nice work!
I left some comments, most of which can also be applied to the rest of the code.
Some general things to do:
- put files under `landing-page/`
- fix formatting (take a look at how it was before)
- don't use `any`, define TS types/interfaces instead
- drop unneccesary `<>`
- let's extract svgs, I know it is a bit beyond initial scope of this PR but it makes sense in order to improve readibility.

I think this should be it!

2024-07-09 09:12 UTC, Martinsos commented on template/app/src/client/components/Client.tsx
> +export default function Client() {
Should be plural!

2024-07-09 09:12 UTC, Martinsos commented on template/app/src/client/components/Client.tsx
> +                  <path
While at it, let's find a way to not have these svgs inlined like this, they make it very hard to read the code, so let's break those out too.
We can do it by having additional variables/functions to hold each svg at the end of the file, or we can extract them as separate svg files, I am not sure what is better -> separate svg files sounds best but I would probalby do a tiny bit of research first. Would love to hear your reasoning!

2024-07-09 09:12 UTC, Martinsos commented on template/app/src/client/components/FAQ.tsx
> +export default function FAQ({faqs}: any) {
Let's not use `any`, instead let's define a TS type (interface) for `faqs` and use that.

2024-07-09 09:12 UTC, Martinsos commented on template/app/src/client/components/Feature.tsx
> +	<>
I don't think you need to `<>` aroudn everything in this case?
Also, formatting is a bit too aggressive -> we don't have a formatter at the moment so sorry about that, but take a look at how origianl file was formatted.

2024-07-09 21:02 UTC, manjhss commented
@Martinsos I made all the changes you mentioned and also seperates svgs in icons folder

2024-07-09 21:28 UTC, manjhss commented
@Martinsos i accidently push above commit (fe77c97), i have  no idea how can i delete or remove, but rest commits can be merged..

2024-07-11 08:39 UTC, Martinsos requested changes

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/Clients.tsx
All right this is now much easier to read, nice! Awesome job on extracting these logos.

Likely final suggestions here:
1. Let's rename those so it is clear they are icons: `AstroIcon`, `ChatGptIcon`, `PrismaIcon`, ... . Or `Logo`, or whatever you think fits best. I guess `Icon` since they are in `icons`. Although logo sounds a tiny bit more on spot (maybe we can rename that dir to `logos`.
2. Actually that is OpenAi logo, not ChatGpt logo, although they are easy to confuse :)!
3. Can you indent everything in `return (` so it starts 2 spaces from start of return, instead of 5 as it is right now? So
```jsx
  return (
    <div className=...
      <h2 ...
```
4. I see now that divs that wrap each logo are identical: `<div className='flex justify-center ...`. It might make sense to extract that then, with `[SalesforceLogo, PrismaLogo, AstroLogo, OpenAiLogo].map(logo => ...)`? Or alternatively extracting that div as a helper component and using it that way! yeah that could be also fine.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/Clients.tsx
> +		<div className='flex justify-center col-span-1 max-h-12 w-full object-contain dark:opacity-80'>
Indentation is also too deep here, let's use 2 spaces.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/FAQ.tsx
> +	    <div className='mt-32 mx-auto max-w-2xl divide-y divide-gray-900/10 dark:divide-gray-200/10 px-6 pb-8 sm:pb-24 sm:pt-12 lg:max-w-7xl lg:px-8 lg:py-32'>
Indentation is messed up

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/Feature.tsx
> +	    <div id='features' className='mx-auto mt-48 max-w-7xl px-6 lg:px-8'>
Indentation is messed up.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/Feature.tsx
Let's rename this file/component to Features -> plural. Haven't noticed this before.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/Footer.tsx
> +	  <div className='mx-auto mt-6 max-w-7xl px-6 lg:px-8 dark:bg-boxdark-2'>
Messed up indentation.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/Header.tsx
> +	  <header className='absolute inset-x-0 top-0 z-50 dark:bg-boxdark-2'>
Messed up indentation.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/Hero.tsx
> +	    <div className='relative pt-14 w-full '>
Messed up indentation.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/LandingPage.tsx
> +	  {/* Header */}
No need for this comment anymore.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/LandingPage.tsx
>          {/* Hero section */}
This comment is also redundant -> and the others below.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/Testimonial.tsx
Let's rename it to Testimonials -> plural.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/Testimonial.tsx
> +	    <div className='mx-auto mt-32 max-w-7xl sm:mt-56 sm:px-6 lg:px-8'>
Messed up identation

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/icons/Astro.tsx
> +	<svg viewBox='0 0 256 370' xmlns='http://www.w3.org/2000/svg'>
Messed up indentation.

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/icons/ChatGPT.tsx
> +	<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMidYMid' viewBox='0 0 256 260'>
indentation

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/icons/Astro.tsx
> +import React from 'react'
Redundant?

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/icons/Prisma.tsx
> +	<svg width={48} height={48} viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'>
indentation

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/icons/Salesforce.tsx
> +	<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 273 191'>
indentation

2024-07-11 08:39 UTC, Martinsos commented on template/app/src/client/landing-page/types.ts
Instead of having a separate types.ts file like this, it would be better to have types next to where they are used / relevant. We aim for organizing code vertically (by domain / what it does), not by types (what it is). So let's drop this file and put types directly where they are used. You don't even have to create interfaces and all, you could directly defined them in the function definitions, since these types likely won't be used in other places.

2024-07-11 11:44 UTC, manjhss commented
@Martinsos I made all the changes but having issue in indentation, in my IDE code is in good format, but while pushing here code is in bad format :/

2024-07-11 15:15 UTC, Martinsos commented
> @Martinsos I made all the changes but having issue in indentation, in my IDE code is in good format, but while pushing here code is in bad format :/ i have no idea how can fix it...

Probably has to do with spaces / tabs! What I would recommend in general is using spaces and have editor show them exactly as they are, to avoid issues like this.

2024-07-11 15:24 UTC, Martinsos reviewed
Ok we are close! Last couple of comments. But we will need to take care of that indentation -> now it is super indented! You should be able to set it up in your editor.

2024-07-11 15:24 UTC, Martinsos commented on template/app/src/client/landing-page/_components/Clients.tsx
Why is directory _components prefixed with _? It is ok that they are all grouped under `components`, but this `_` is unusual to me.

2024-07-11 15:24 UTC, Martinsos commented on template/app/src/client/landing-page/_components/FAQ.tsx
> +type FAQ = {
Let's use `interface`, TS Handbook recommends using `interface` over `type` in typical situations when possible. Same for other types.

2024-07-15 10:22 UTC, Martinsos requested changes
Ok @manjhss nice job! I would say this is all, except for following things:
1. Indentation is off for JSX.
2. We have conflicts with `main` branch.
3. We need to update the demo app (opensaas-sh/app) and also docs if needed.

Regarding (1), if you don't manage to fix it (and you said you were having trouble with that), no big deal, we can fix indentation ourselves before the merge.
Regarding (2), since the big vertical reorganization is still happening, might be best if we wait just a bit for it to be finished and then resolve the conflicts. New version of open-saas should be released in a couple of days, so we can do it after that.
Regarding (3) -> we will take care of that as it is a bit complex!

So this is it really -> thanks for the good work, let's give it a couple of days of rest till new version of OpenSaas is released, and then we will take over the PR and do final stuff that is needed to merge this!

2024-07-16 22:08 UTC, Martinsos commented
Ok this should be it! I fixed indentation (replaced tabs with spaces), updated the demo app (app_diff/), and there were no updates for the docs needed I believe.

2024-07-16 22:09 UTC, Martinsos reviewed
Done from my side!

2024-07-17 09:10 UTC, vincanger commented on template/app/src/landing-page/components/Clients.tsx
> +          [<SalesforceLogo />, <PrismaLogo />, <AstroLogo />, <OpenAILogo />].map((logo, index) => (
love this!

2024-07-17 09:10 UTC, vincanger commented on template/app/src/landing-page/components/Features.tsx
> +interface Feature {
🙏

2024-07-17 09:12 UTC, vincanger approved these changes
Looking very clean and organized. Thanks so much for your hard work @manjhss 🙏

@Martinsos the update to the app_diff is just a dead link I fixed. Ran the tests and they all passed. Everything looks good :)

2024-07-17 09:24 UTC, merged