Improved seo docs page
wasp-lang/open-saas pull request #297
Opened 2024-10-20 10:04 UTC by NeroxTGC

## Description

> Describe your PR! If it fixes specific issue, mention it with "Fixes # (issue)".

## Contributor Checklist

> Make sure to do the following steps if they are applicable to your PR:

- [ ] **Update e2e tests**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/template/e2e-tests](/template/e2e-tests) also.
- [ ] **Update demo app**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/opensaas-sh/app_diff](/opensaas-sh/app_diff) also. Check [/opensaas-sh/README.md](/opensaas-sh/README.md) for details.
- [ ] **Update docs**: If needed, update the [/opensaas-sh/blog/src/content/docs](/opensaas-sh/blog/src/content/docs).

2024-10-22 19:00 UTC, Martinsos reviewed
Awesome work @NeroxTGC , thanks for this!
I think this generaly makes sense and looks good -> I left some comments, but nothing major I believe, let's take care of those and we can merge!

2024-11-22 11:59 UTC, NeroxTGC commented
@Martinsos I finished updating the document with your suggested changes. If you like, check it one last time.

I've also created a `robots.tsx` default for the template and fixed the missing `alts` on the images to make the Landing Page 100% Seo Score.

2024-11-28 16:24 UTC, Martinsos commented on opensaas-sh/blog/src/content/docs/guides/seo.md
> +import {HelmetProvider } from 'react-helmet-async';
```suggestion
import { HelmetProvider } from 'react-helmet-async';
```

2024-11-28 16:24 UTC, Martinsos commented on opensaas-sh/blog/src/content/docs/guides/seo.md
> +      <>
@NeroxTGC what about this one?

2024-11-28 16:24 UTC, Martinsos commented on opensaas-sh/blog/src/content/docs/guides/seo.md
> +Now, you can set page-specific meta tags  in your React components.
```suggestion
Now, you can set page-specific meta tags in your React components.
```

2024-11-28 16:24 UTC, Martinsos commented on opensaas-sh/blog/src/content/docs/guides/seo.md
> +import { Helmet, HelmetProvider } from 'react-helmet-async';
redundant import of helmet provider

2024-11-28 16:24 UTC, Martinsos commented on opensaas-sh/blog/src/content/docs/guides/seo.md
> +- [Schema validator](https://validator.schema.org/)
@NeroxTGC ping on this - what do you think?

2024-11-28 16:30 UTC, Martinsos requested changes
@NeroxTGC nice, there is still some stuff to fix though, I commented!

2024-11-28 16:30 UTC, Martinsos commented on template/app/public/robots.txt
> +Disallow: /auth/
hm so api and auth here - do we need that? because those are parts of the server, and server is not hosted at the same url as client, at least not usually.

2024-12-13 12:33 UTC, NeroxTGC commented on template/app/public/robots.txt
> +Disallow: /auth/
updated, you are right.

2024-12-13 12:37 UTC, NeroxTGC commented
### Seo Guide

- Removed the extra `<>`.
- Removed redundant `HelmetProvider`.
- Shortened the section on structured data.

---
### OpenSaaS template

- Removed `/api/` &  `/auth/` from `robots.txt`


@Martinsos I don't think I've missed anything now, right?

2024-12-14 05:54 UTC, Yherealtita approved these changes

2026-08-14 02:18 UTC, closed without merging