Playwright tests & CI
wasp-lang/open-saas pull request #69
Opened 2024-03-05 15:38 UTC by vincanger

Adding some basic playwright tests, as well as a couple github workflows.

Questions:
1. should we include these tests on the main branch, or perhaps only on a feature branch, as well as the `deployed-version` branch (the branch which gets deployed to opensaas.sh)? this way, we can test new features before updating the template on `main`, as well as the app that gets deployed to opensaas.sh without adding a lot of complexity to the template the users initially get. if users DO want to opt in to tests/CI, we can instruct them on how to do so in the docs.
2. should e2e tests for the template test stripe checkout flow? if so, we'd probably need to build a modified feature branch and create a staging environment, because, at the moment, the template on `main` ships with username and password auth only to start, as it doesn't require any ENV VARS and allows the user to get started right away, but it is not compatible with Stripe checkout. Therefore, if we want extensive testing of the template, we should probably go the feature branch/staging environment route...

2024-03-06 21:18 UTC, Zeko369 requested changes

2024-03-06 21:18 UTC, Zeko369 commented on app/playwright/tests/utils.ts
> +  const password = `password${Math.random().toString(36).substring(7)}!`;
Maybe use `crypto.randomUUID()` since it's more obvious what it does, "this looks like some random code"

2024-03-06 21:18 UTC, Zeko369 commented on app/playwright/tests/utils.ts
> +};
Import from Prisma?

2024-03-06 21:18 UTC, Zeko369 commented on app/playwright/tests/unpaidUserTests.spec.ts
> +      return false;
Maybe use just the path since it's easier to run it against non localhost:3001 targets in that case

2024-03-06 21:18 UTC, Zeko369 commented on app/playwright/tests/unpaidUserTests.spec.ts
> +  await loggedInPage.waitForURL('http://localhost:3000/demo-app');
I'll just comment here but applies everywhere, use `/demo-app` instead of `http://localhost:3000/demo-app` so it's easier to run against different hosts

2024-03-06 21:18 UTC, Zeko369 commented on app/playwright/tests/paidUserTests.spec.ts
> +  ]);
Maybe add a test to see what happened (that the response got shown)

2024-03-06 21:18 UTC, Zeko369 commented on app/playwright/tests/unpaidUserTests.spec.ts
> +  ]);
Maybe add a test to see what happened (that the error got shown)

2024-03-06 21:18 UTC, Zeko369 commented on app/playwright/tests/landingPageTests.spec.ts
> +    expect(page.getByRole('heading', { name: 'Features' })).toBeTruthy();
`.toBeVisible()`

2024-03-06 21:18 UTC, Zeko369 commented on app/playwright/tests/landingPageTests.spec.ts
> +    await page.getByRole('link', { name: 'Get started' }).click();
Add `await page.waitForURL('/the-path-this-leads-to')`

2024-03-07 15:46 UTC, Martinsos requested changes
@vincanger I did a review of everything but the Playwright tests themselves -> once we take care of most of the stuff, I can also review those into more details. I was instead focusing on how it is all orchestrated.

Some general stuff:

Normally, you would run CI on every PR and on `main` branch. That way we get CI checks done when for the PR, so we know all is fine before merging into `main`, and then also on `main`, again, just to ensure `main` is all good after the merging and something did go wrong.

This is also how we do it for `wasp` repo.

You mentioned testing Stripe but for that you need a different type of auth, not username & pass, and how you could handle that using different git branches.
In general, I would say that is not the usual approach -> you don't want to get entangled into maintaining multiple branches at the same time -> instead normally you would aim for having these other versions as some kind of example apps in the repo, that you run these tests on. So maybe there would be "examples" dir at the top level of the repo, and you would test this stuff there. Not saying that doing something with branches can't be done, maybe it can and maybe it is potentially interesting, but I wouldn't consider it as a go-to option.

Btw, we are likely to switch open saas to using email&pass very soon because it has a good support now (with 0.12) for running in dev with no setup at all, so maybe that will help a bit for Stripe testing?

As for giving them these e2e tests or not, setup via Github Actions -> my first instinct is to let them have it, by default, since it is nice, does the tests for you, and we give them instructions how to delete it if they don't like it.

ALthough retag-commit is problematic, we don't want them to have that one hm!

If they use this template via `wasp new`, then it is easy, but if they clone the Github repo as a template, then I don't know how we can do this properly.
I am tempted to say we allow using it only via `wasp new`! It gives us more control, we can do what we want here in repo and `wasp new` can delete some files upon download, or download only some files (although they don't get git repo immediately).

2024-03-07 15:46 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +
You will likely also want to pin down the node version in this node action, so we are explicit about it. Check how we are doing it for `wasp`, we have a step which installs specific version of node.

2024-03-07 15:46 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +        run: curl -sSL https://get.wasp-lang.dev/installer.sh | sh -s
So this installs any version of Wasp. If we release new major version of Wasp, but open-saas is not yet on it, this will start breaking. Maybe you should rather pin down the version of Wasp here?

2024-03-07 15:46 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +          key: node-modules-${{ hashFiles('app/package-lock.json') }}
I would add some more keys to this cache.
I would have: `os`, `package-lock`, `node version`. Because if you add mac in the future, you don't want to pull in node_modules built for ubuntu. Or if we change node version, we don't want to pull in node_modules built for old version. These three should be enough to always pull in the correct node_modules.
We are also now fixing this in Wasp because we are missing it there also, I reached out to @infomiho regarding that. So unless I am wrong, this is something we should do.

2024-03-07 15:46 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +      - name: Install Node.js dependencies
Why are we installing deps like this? Shouldn't we use Wasp to install dependencies?

2024-03-07 15:46 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +      - name: Setup Env Vars not in github secrets
Ok so we just "dumb" copy them right? Aha, so some of them are in Github secrets? Seems to me like you set all of them to example stuff? I am a bit confused how the `cp .env.server.example .env.server` directly reflects "Setup Env Vars not in github secrets", feels like there is a part of story missing here, some assumptions that are not explicitly handled and might change and breaking things in the future.

2024-03-07 15:46 UTC, Martinsos commented on .github/workflows/retag-commit.yml
> +name: Retag Commit
So what is our reasoning behind this Action -> it keeps assigning this tag to the last commit on `main`, right?

I guess that makes sense! It means people doing `wasp new` and just copying this template are getting the same version.

WHat happens when we want to update to new Wasp version -> we update the version here in this action, and push it to `main` together with the rest of the changes that update open-saas to this new version, right? Ok yeah, sounds good!

Let's add to README something about this, that explains that this is happening and what we have to do to get open-saas to use new Wasp version.

2024-03-07 15:46 UTC, Martinsos commented on .github/workflows/retag-commit.yml
> +          git push origin wasp-v0.12-template
You might want to extract this `wasp-v0.12-template` value as an ENV VAR here (whatever Github Actions support, be it on yaml level or env var level), to remove duplication, because I can imagine in the future somebody easily forgetting to update one of these, or missing a letter, or whatever.

2024-03-07 15:46 UTC, Martinsos commented on app/ci-start-app.js
> +const cp = require('child_process');
Hm what is this, we would do well with some explanation here. Idealy we would have this here, in `app/`, because it now became part of the template!

2024-03-07 15:46 UTC, Martinsos commented on app/main.wasp
> +    version: "^0.12.2"
Sure, but probably shouldn't be part of this PR, right?

2024-03-07 15:46 UTC, Martinsos commented on app/package-lock.json
We didn't have this previously, did we? Why do we have it now?

2024-03-07 15:46 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +          key: node-modules-${{ hashFiles('app/package-lock.json') }}
Thinking about this more -> do we want to have package-lock.json for our open-saas template? What are we testing really? Maybe we are testing how it works for a new open-saas app, that just pulled in the latest packages? This does make our tests flaky hm. Ok this goes together with the question of, should the app/ contain package-lock at all.
The problem is, Wasp doesn't yet have good support for package-lock. Even if you have it in app/, the generated .wasp/.../client and .wasp/.../server don't have package-lock's, and you are not really properly guarding yourself. So I wouldn't do it at all probably for now, until we figure that out. Maybe open an issue for it, to look into this and we can discuss it there, but wouldn't bother with it right now.

2024-03-07 15:46 UTC, Martinsos commented on app/package.json
> +    "example-app:playwright:ui": "playwright test --ui"
@vincanger can you give me a bit of reasoning on all this? Are we ok with users having this in their open-saas project once they copy the template? Are they going to be able to understand this -> what is it for, and how were choices here made, how to modify this if needed?

2024-03-07 16:27 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +          key: node-modules-${{ hashFiles('app/package-lock.json') }}
Ok maybe I had s bit of a braibfart here - it is normal for us with wasp 0.12 to have package-lock actually. But our story about package-locks is indeed still shaky. And this is a template so I wonder if having package-lock in it makes sense, that still stands. Hm. We should think this through a bit.

2024-03-08 14:41 UTC, Martinsos commented on app/package-lock.json
Hm I take this back, we have it because of Wasp 0.12 which adds it, right? Still, the question is do we want to have in the template -> that is something to consider.

2024-03-08 15:26 UTC, vincanger commented on app/playwright/tests/utils.ts
> +};
password doesn't exist on the user model since v0.12.x uses a new obfuscated auth structure

2024-03-08 15:42 UTC, Martinsos commented
@vincanger and I discussed the structure of e2e tests a bit, decided they were too integrated with the Wasp app (they were entangled into its package.json and similar), we agreed to separate them so they are self-contained.

2024-03-18 14:52 UTC, vincanger commented on .github/workflows/e2e-tests.yml
> +
i believe I managed to do this via this sep:

```sh
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wasp
        run: curl -sSL https://get.wasp-lang.dev/installer.sh | sh -s

      - name: Docker setup
        uses: docker/setup-buildx-action@v3
 ```

2024-03-18 14:57 UTC, vincanger commented on .github/workflows/e2e-tests.yml
> +        run: curl -sSL https://get.wasp-lang.dev/installer.sh | sh -s
i should probably bump it up to 0.12.4, right?

2024-03-18 15:13 UTC, vincanger commented on .github/workflows/e2e-tests.yml
> +      - name: Setup Env Vars not in github secrets
ok i renamed this to Setup Dummy Env Vars. they are just placeholders to keep the app from crashing. I will add in the docs that you need to add certain env vars to the github env depending on your tests

2024-03-18 15:19 UTC, vincanger commented on app/main.wasp
> +    version: "^0.12.2"
:(

2024-03-18 15:19 UTC, vincanger commented on app/package-lock.json
moved everything to the `e2e-tests` directory as its own npm project

2024-03-18 15:20 UTC, vincanger commented on app/package.json
> +    "example-app:playwright:ui": "playwright test --ui"
same here

2024-03-18 15:51 UTC, vincanger commented
ok @Martinsos -- I made the requested changes. could you review again, please?

2024-03-21 11:36 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +        run: curl -sSL https://get.wasp-lang.dev/installer.sh | sh -s
Yeah and I see you bumped it, great!

What you will likely want to do is update this version number any time you update the Wasp version that open-saas uses. If you forget, I think this will just crash, so that is good, that will remind you. But what you could also do is a add a bit into README.md on what needs to be done when updating the version of Wasp that open-saas uses, and there you can note that it also needs to be updated here. You will know the best if that makes sense or not so I will leave it to you to decide if that is valuable.

2024-03-21 11:40 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +      - playwright-tests
Since this is a branch toward `main`, I don't think you need this line with `playwright-tests` here, it is being triggered anyway.

2024-03-21 11:40 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +          key: node-modules-${{ hashFiles('app/package-lock.json') }}
Ok, you added OS and node version, which is great. I am just curious, you added them in front of `node-modules` part of the key, why is that? I think it doesn't matter much, but I would naturally put it after, so if I am reading that key somewhere, I first read `node_modules`, aha, these is a cache of node modules, and then come the details of the environment it was cached for (os, node version, package-lock version).

2024-03-21 11:41 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +          key: node-modules-${{ hashFiles('app/package-lock.json') }}
What remaains open is the question of package-lock.json. I wrote bunch a stuff above, said we should discuss -> what is your line of thinking about it?

2024-03-21 11:54 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +          key: node-modules-${{ hashFiles('app/package-lock.json') }}
Oh, another question -> what about e2e-tests? They are also an npm project. They also have their own node_modules, and their package-lock.json and so on. What about them? Do we care about their package-lock.json?

Btw, I don't know how much details you know about how `actions/cache@v4` GH action works, but I remember I was surprised a bit, because it won't update the cache if it managed to pull it. So either if finds it and pulls it in, or it doesn't and then will upload the new cache.
I found this problematic for `waspc`: https://github.com/wasp-lang/wasp/blob/main/.github/workflows/waspc-ci.yaml#L117 -> because I didn't want the whole cache dropped if one dependency changed. I wanted it to be more like the normal behaviour on my dev machine -> restore the last state of npm packages cached on the machine and once done, just update it. But instead I was getting more of "all or nothing" situation. Which for Haskell was a major issue, because if cache gets dropped, it takes 20 minutes to install all the deps! Even though like only 1 dep got added, I would loose thousands of them that were already in the cache. Which is why I did a bit more involved setup there.

You might want to do something similar here, or not, I am not 100% sure yet. But there is also the question of wasp version, I just realized -> let's say everything remains the same, node version, os version, package-lock.json in app, but version of wasp changes. Your cache key will not change, I think? Or maybe it will because package-lock.json will change? I think it is possible it won't change, if new wasp version brought a change in deps of "framework" code. So thinking about it, wasp version should also probably be part of that npm cache.

So there are two things to discuss here:
- how does actions/cache really behave and how we want to use it then
- which part's of this project are contributing to the `./npm` and therefore should be considered while caching it (at the moment I would say user's package.json, e2e package.json, and also wasp's framework code package.json's (which can be tied to wasp version)).

2024-03-21 11:56 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +      - name: Install Node.js dependencies
So you uncommented this out. Why not delete it?

Aha, but you do have it a bit down there, but now running it in `e2e-test/`. Ok.

2024-03-21 12:15 UTC, Martinsos commented on .github/workflows/retag-commit.yml
> +# NOTE: this action is only necessary for development of the Open SaaS template.
Ha yeah, this is the consequence of using this repo as a template, we now have redundant stuff like this.

This is why I would be highly tempted to remove the option to copy this as a template, and just have them pull it through `wasp` CLI (as they can do right now), where we can then do the necessary cleanup as needed. Might be worth opening an issue for this, and following up on it. It will make it easier for both us and them I think.

2024-03-21 12:15 UTC, Martinsos commented on .github/workflows/retag-commit.yml
> +# This action keeps assigning the TAG_NAME to the last commit on main.
Great, but I still think this should be in README.md, under `Contributors` section. When I am doing stuff on a repo, I will be looking into README.md for instructions on what I have to do when I am 1) updating version 2) releasing 3) something else. I probably will never even check out this file otherwise.

Same is for the users, we should probably have a section in the README.md that tells them which parts of this repo they should delete once they copy it. As I mentioned, I think there is a better way to handle this, by not allowing forking it as a template, but in the meantime, this is also possible solution.

2024-03-21 12:15 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +      - name: Setup Env Vars not in github secrets
Ok, so this is basically prepping the app so it can be run.

I am wondering if potentially this should be done as a part of e2e-tests logic though (probably inside their package.json). Not sure yet, I have to read more of the code.

2024-03-21 13:14 UTC, Martinsos commented on e2e-tests/tests/paidUserTests.spec.ts
> +  // Click button:has-text("Add task")
Redundant comment

2024-03-21 13:14 UTC, Martinsos commented on e2e-tests/tests/paidUserTests.spec.ts
> +  // Fill input id="description" with "create presentation"
Redundant comment (I guess it was here for copilot).

2024-03-21 13:14 UTC, Martinsos commented on e2e-tests/tests/paidUserTests.spec.ts
> +  expect(generateScheduleButton).toBeTruthy();
So I am not playwright expert but checking for `toBeTruthy` doesn't sound the same as checking it the button is visible. Maybe that is ok, maybe you don't want to check if it is visible, but just that the dom element exists. But then the comment is potentially wrong?

2024-03-21 13:14 UTC, Martinsos commented on e2e-tests/ci-start-app.js
> +const cp = require('child_process');
Would be intersting to undresatnd a bit better why this script is needed. Because we want to run these two in parallel? There isn't a simpler way? From what I got we have to handle some special case with Prisma, somebody mentioned that? If so, that should be mentioned here as a motivation. I know you copied this from `wasp`, but that means it is confusing there also, let's improve it here if we can.

2024-03-21 13:14 UTC, Martinsos commented on e2e-tests/tests/unpaidUserTests.spec.ts
> +// Create a new test fixture with an unpaid user and a logged in page
Redundant comment.

2024-03-21 13:14 UTC, Martinsos commented on e2e-tests/tests/paidUserTests.spec.ts
> +// Create a new test fixture with a paid user and a logged in page
Redundant comment, code says exactly the same thing (which is great, nice code).

2024-03-21 13:14 UTC, Martinsos commented on e2e-tests/tests/utils.ts
> +  // Fill input[name="username"]
Bunch of redundant comments in this file.

2024-03-21 13:14 UTC, Martinsos commented on e2e-tests/tests/utils.ts
> +  await page.fill('input[name="password"]', user.password || 'password123');
Extract `password123` into a constant `DEFAULT_PASSWORD` and use that in both places.

2024-03-21 13:14 UTC, Martinsos commented on e2e-tests/tests/utils.ts
> +      await prisma.user.delete({ where: { id: user.id } });
Oh ok so this is not only creating a new user, but also deleting any data that user might already have in the database? That sounds a bit unexpected. ALso, if this user is random, how can there be any data from before?
I think either this is not needed, or it is worth considering doing it in a separate piece of logic.

2024-03-21 13:14 UTC, Martinsos commented on app/package.json
> +    "example-app:playwright:ui": "playwright test --ui"
Ok, we figured this stuff out!

2024-03-21 13:15 UTC, Martinsos reviewed
@vincanger nice job with the changes, this is now quite better, getting there!
I left some more comments.

2024-03-21 13:24 UTC, vincanger commented on .github/workflows/retag-commit.yml
> +# NOTE: this action is only necessary for development of the Open SaaS template.
on the other hand, a tag will not create any issues if they fail to remove it from their repo. I could also add a section in the docs that gives them a command they can copy and paste to remove this file. Even if we remove it via `wasp new` we can't stop people from cloning the repo...

2024-03-21 13:26 UTC, vincanger commented on app/package-lock.json
I had Playwright installed on the app, but then removed it and moved it to the e2etests folder

2024-03-21 13:26 UTC, vincanger commented on e2e-tests/tests/utils.ts
> +import { prisma } from '../../app/src/server/utils';
i like to live dangerously

2024-03-21 13:28 UTC, vincanger commented on e2e-tests/package.json
> +    "prisma": "^5.11.0"
i probably forgot to uninstall this

2024-03-21 13:29 UTC, vincanger commented on e2e-tests/tests/paidUserTests.spec.ts
> +  // Fill input id="description" with "create presentation"
haha yes. i'll remove them

2024-03-21 13:35 UTC, vincanger commented on e2e-tests/tests/utils.ts
> +      await prisma.user.delete({ where: { id: user.id } });
as I understand it, the user is created, and then tests are ran against it via line 73 `await use(page)` where it pauses and awaits the completion of the tests. After tests run, the user data is deleted.

2024-03-22 10:14 UTC, vincanger commented on .github/workflows/e2e-tests.yml
> +      - playwright-tests
I left it there to test the action every time I pushed changes to `playwright-tests`. will delete it before we merge!

2024-03-22 10:56 UTC, vincanger commented on e2e-tests/ci-start-app.js
> +const cp = require('child_process');
paging MR. MIHO on this one, too @infomiho

2024-03-22 10:59 UTC, infomiho commented on e2e-tests/ci-start-app.js
> +const cp = require('child_process');
In the original script we are mentioning an issue with the link 🙂 

It boils down to how we check DB connectivity by running Prisma commands and it relies on stdin working properly. This script made it work for us in the CI and none of the fancy parallel npm tooling 🤷🏻‍♂️

2024-03-22 11:00 UTC, vincanger commented on e2e-tests/package.json
> +    "e2e:start-app": "npm run e2e:wait-for-db && cd ../app && wasp db migrate-dev && wasp start",
i don't think this is necessary, since the command `e2e:start-db` is a process being called within `ci-start-app.js`. so db is alwasy cleaned up before starting it.

2024-03-22 11:12 UTC, vincanger commented on e2e-tests/package.json
> +    "e2e:cleanup-db": "(docker container rm $(docker container ls -f name=^wasp-dev-db-OpenSaaS- -q) -f || true) && docker volume rm $(docker volume ls -f name=^wasp-dev-db-OpenSaaS- -q) -f || true",
leaving comments in a json file is kinda weird, e.g. 

```json
"_comment-on-e2e:cleanup-db": "NOTE: the name of the DB container, e.g. name=^wasp-dev-db-OpenSaaS-, is generated by wasp and will match the name of the app definition in your `main.wasp` file, e.g. `app OpenSaaS { }`",
"e2e:cleanup-db": "(docker container rm $(docker container ls -f name=^wasp-dev-db-OpenSaaS- -q) -f || true) && docker volume rm $(docker volume ls -f name=^wasp-dev-db-OpenSaaS- -q) -f || true",
```

2024-03-24 23:05 UTC, infomiho commented on e2e-tests/tests/utils.ts
> +import { prisma } from '../../app/src/server/utils';
Ideally, we don't need to manipulate the DB directly when we are doing e2e tests. Somehow we should be able to perform all the tests steps via user interaction only. If there are some steps that need to be mocked for example, Stripe payments, we should maybe short-circuit it some custom env vars in the app which we set to `true` when running the e2e tests?

That being said, I've seen here for example that they do use direct DB manipulation in tests: https://www.prisma.io/blog/testing-series-4-OVXtDis201

If we need to do it, ideally, we should not import Prisma from the Wasp project, but we would set up Prisma in the `e2e-tests` project:
1. Install Prisma as a dependency
2. Init the `PrismaClient` by referencing the schema file from the Wasp project `npx prisma generate --schema=...`
3. Use the `PrismaClient` by importing it from `@prisma/client`

2024-03-24 23:05 UTC, infomiho commented on e2e-tests/tests/utils.ts
> +import { prisma } from '../../app/src/server/utils';
I'll try to get this working tomorrow and report back 👍

2024-03-25 02:54 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +      - playwright-tests
Soudns good! I think you can delete it right now though, because you have a PR now, so it will be run for it anyway, right? Because it is a PR.

2024-03-25 02:57 UTC, Martinsos commented on .github/workflows/retag-commit.yml
> +# NOTE: this action is only necessary for development of the Open SaaS template.
Sure, but this is not the only thing that doesn't make sense for them, there are multiple things that are a mismatch between what we need for this repo, and what the template for them should look like.
As for cloning -> well we can't stop them from cloning the repo, but we can direct them to not do it. If we say in docs they should pull it via `wasp new open-saas`, they will follow that.

2024-03-25 02:59 UTC, Martinsos commented on app/package-lock.json
Yup! Let's make sure though that we don't have these old changes here then.

2024-03-25 03:01 UTC, Martinsos commented on e2e-tests/tests/utils.ts
> +import { prisma } from '../../app/src/server/utils';
Yeah I get what you mean by ideally not manipulating the database, you are right, that would be perfect.
That said, sometimes it can be practical to manipulate the database.
And in that case, yeah it would be better if we have local prisma that uses Wasp's schema.
So I agree with everything you said here, sounds right @infomiho ! Interested to see what you come up with.

2024-03-25 03:02 UTC, Martinsos commented on e2e-tests/package.json
> +    "e2e:cleanup-db": "(docker container rm $(docker container ls -f name=^wasp-dev-db-OpenSaaS- -q) -f || true) && docker volume rm $(docker volume ls -f name=^wasp-dev-db-OpenSaaS- -q) -f || true",
Oh yeah I know! But you did fine there I think.

2024-03-25 04:32 UTC, Martinsos commented on e2e-tests/playwright.config.ts
> +  webServer: process.env.CI
@vincanger you put a :rocket: emoji but I don't see any comment added in the code: am I seeing something wrong? Or maybe you didn't push these changes?

2024-03-25 04:32 UTC, Martinsos commented on e2e-tests/tests/landingPageTests.spec.ts
> +import { DOCS_URL } from '../../app/src/shared/constants';
Yeah let's hardcode it then!

2024-03-25 04:36 UTC, Martinsos commented on e2e-tests/tests/paidUserTests.spec.ts
> +  // Fill input id="description" with "create presentation"
Same like in the comment above, you put a :rocket: but I can still see the comment.

2024-03-25 04:38 UTC, Martinsos commented on e2e-tests/tests/paidUserTests.spec.ts
> +  // Fill input id="description" with "create presentation"
Ok my bad, Github took me to the old commit which is why I thought these are not yet done! All good here.

2024-03-25 04:43 UTC, Martinsos commented on e2e-tests/ci-start-app.js
> +const cp = require('child_process');
Ok cool, let's make sure to cover this with the comment then!

2024-03-25 04:59 UTC, Martinsos commented on e2e-tests/tests/utils.ts
> +      await prisma.user.delete({ where: { id: user.id } });
Ah got it! I completely missed the `use(page)` line.

@infomiho I think database deletion is done before running all the e2e tests, but this deletion here is done after every "single" test I guess, that uses this fixture, so that makes sense to me? Keeping it clean for other tests coming after it.

What @infomiho is proposing those is compelling though, doing tests without having to explicitly "doctor" the database. But if that is quite harder / less practical, then I don't mind us doctoring it.

2024-03-25 05:07 UTC, Martinsos commented on e2e-tests/playwright.config.ts
> +  webServer: process.env.CI
Hm I still dont' quite get it!

Why would port conflicts happen in CI? What does it even mean you run the web server on CI, what is web server here? Why does it help in local development that we do this stuff manually? I think I am missing quite a bit of context / knowledge here, which is why I don't understand this, but we can assume other people reading this might also be missing this context, so it would be great if we enriched the comment to make it understandable for me/them.

2024-03-25 05:20 UTC, Martinsos commented on e2e-tests/package.json
> +    "e2e:start-app": "npm run e2e:wait-for-db && cd ../app && wasp db migrate-dev && wasp start",
So `ci-start-app.js` script runs two things at the same time, in parallel: `e2e:start-db` and `e2e:start-app`, if I am correct.

What seems like a potential problem to me is that, due to that, first part of `e2e:start-db`, which is db cleanup, and also first part of `e2e:start-app`, which is waiting for db, may run at the very same time, possibly resulting in `wait-for-db` running a tiny bit sooner, enough to detect already running db and saying "ok, great, it is there", only to then have that same database cleaned up, causing trouble down the line, because now migrate-dev is being run but db is not ready yet.

@infomiho I believe this is same/similar as in e2e tests in Wasp, so I am also interested what you think about this, am I correctly identifying this as a potential problem, or I am overlooking something?

2024-03-25 10:17 UTC, infomiho commented
@vincanger here's a way you can setup Prisma inside of the `e2e-tests` project and avoid importing stuff from the Wasp app :)

https://github.com/wasp-lang/open-saas/pull/86

2024-03-25 14:02 UTC, vincanger commented on .github/workflows/retag-commit.yml
> +# NOTE: this action is only necessary for development of the Open SaaS template.
ok. sounds good. i'll go ahead and remove the option to use this repo as a template and add info in the readme / docs for prioritizing `wasp new open-saas`

2024-03-25 14:19 UTC, vincanger commented on e2e-tests/tests/utils.ts
> +import { prisma } from '../../app/src/server/utils';
merged miho's PR that creates a new Prisma Client in the e2e-tests folder based on the prisma.schema file

2024-03-25 14:42 UTC, vincanger commented on e2e-tests/ci-start-app.js
> +const cp = require('child_process');
this comment is already below starting on line 11

2024-03-25 14:43 UTC, vincanger commented on e2e-tests/package.json
> +    "e2e:start-app": "npm run e2e:wait-for-db && cd ../app && wasp db migrate-dev && wasp start",
i believe this is covered by the comment in `ci-start-app.js` on line 11

2024-03-25 22:17 UTC, Martinsos commented on e2e-tests/package.json
> +    "e2e:start-app": "npm run e2e:wait-for-db && cd ../app && wasp db migrate-dev && wasp start",
@vincanger from what I am understanding, that comment is talking about the specific issue of prisma hanging if not run via this script that we have here, and is basically the reason why we have this script. But it doesn't address what I am talking about here, there are separate concerns, not connected.

2024-03-25 22:36 UTC, Martinsos commented on e2e-tests/playwright.config.ts
> +  webServer: process.env.CI
Ah ok, now I think this is much clearer!

Ok, so I will try to rephrase this, to see if I got it right.

What we want, is to run a Wasp app, and then when it is running, we want to run playwright, which then interacts with it and tests it that way (e2e tests).

Playwright has this option, `webServer`, which tells it how to run the actual thing you want to test, in our case "Wasp app". So it will first run that, and then go for testing it.

So just to extra clear, it is not a "playwright webserver" in the sense that it is some kind of web server that playwright runs for its purposes to execute tests, it is instead our wasp app that it is executing tests against.

However, we have an issue, where after playwright is done, the whole things hangs for some reason, and that is annoying as you can't easily just do `wasp start` after it, as it will get into conflicts with it (I guess ports are occupied?).

This isn't a problem in CI, because we won't be running anything after it (hopefully? What if we do in the future?), we will just close the machine.

But it is an issue in development. So in development, we do it differently: we do it manually, by running `wasp start` ourselves, and then playwright won't try to run it on its own, because it sees that webserver is already running (so the docs say here https://playwright.dev/docs/test-webserver), so it will just the existing one already.

Ok! It doesn't have to be this long, the explanation, but I think you can improve your comment even a bit more with some of the info from here. Imagine Matija is reading this -> we want him to know, after reading it, the basic gist of what is it about, without having to go learn Playwright, or knowing what "webserver" stands for in this specific context.

Btw, this sucks a bit, that we have different behaviours during local development and during CI, because of this bug. I am tempted to say we should use the same approach both in CI and development -> let's also use `wasp start` in CI then! Aha, but we can't, because `wasp start` has issues in CI, which is why we have that script. Oh man. Ok, comment will be enough for now, until we properly resolve this.

Btw, i am for fixing this bug, it would be enough to just do basically catch that kill signal arrived and then forwarding it to spawned processes, in the `ci-start-..` script. so something like this:

```
// Spawn a child process
const child = spawn('command', ['args']);

// Listen for the parent process to be killed
process.on('SIGINT', () => {
    console.log('Received SIGINT. Exiting and killing child process.');
    child.kill('SIGINT'); // Kill the child process
    process.exit(); // Exit the parent process
});
```

2024-03-25 22:44 UTC, Martinsos commented on e2e-tests/tests/utils.ts
> +      await prisma.user.delete({ where: { id: user.id } });
What did we do here at the end? @vincanger feel free to close this if we are done here.

2024-03-25 22:45 UTC, Martinsos commented
@vincanger @infomiho I did another quick round of comments.
@vincanger let's dig down into any remaining open comments and figure out what we need to do to bring them to resolution!

2024-04-03 14:46 UTC, vincanger commented on e2e-tests/playwright.config.ts
> +  webServer: process.env.CI
ok @Martinsos I played around with this some more and ran into the issue. Playwright sends a SIGKILL signal and it wasn't being passed down to the child processes because we had `const spawnOptions = {detached: true};`. It works when it's set to false, and I'm not sure why we had it set as detached before (maybe @infomiho knows).

The issue we still have though is that the db docker container is still running on port 5432 and if we try to start the db via `wasp start db` we get an error. Not sure what the best solution would be, because we can't clean up the db via a SIGKILL signal...

2024-04-03 14:51 UTC, vincanger commented on e2e-tests/tests/utils.ts
> +      await prisma.user.delete({ where: { id: user.id } });
@Martinsos like you said, the deletions are done after every single test, to keep it clean for other tests coming after it.

Off the top of my hand, I can't imagine how I would test things that need a logged in user without directly accessing the DB. Could you give me an example @infomiho? how could I test adding tasks and generating an AI schedule without logging in a user and generating tasks, etc?

2024-04-03 14:59 UTC, vincanger commented on e2e-tests/package.json
> +    "e2e:start-app": "npm run e2e:wait-for-db && cd ../app && wasp db migrate-dev && wasp start",
@Martinsos I never ran into an issue with `wasp start` being run even if  a docker container was still live on port 5432, but i tested it as you suggested, by running `e2e:cleanup-db` before starting the node script and it works fine, so to be safe I made the change as you suggested

2024-04-04 09:26 UTC, vincanger commented on e2e-tests/ci-start-app-and-db.js
> +      detached: false,
this was previously set to `true` and because playwright sends a SIGKILL signla, the child processes weren't receiving them.

2024-04-04 09:28 UTC, vincanger commented on e2e-tests/package.json
> +    "e2e:set-db-name": "chmod +x ./setupDatabaseName.sh && ./setupDatabaseName.sh",
i've added this script to make sure we're setting the correct DATABASE_URL when running the github action. When deploying it with the database name given locally, it failed. For whatever reason, the hash is different when running via CI

2024-04-04 15:24 UTC, Martinsos commented on e2e-tests/ci-start-app-and-db.js
> +};
So regarding the database cleanup: what we could do is have a function `cleanup` and then call it both here, if code !== 0, and also if we receive a sigkill, sigterm, or whatever is the most appropriate signal.

2024-04-04 15:24 UTC, Martinsos commented on e2e-tests/tests/utils.ts
> +      await prisma.user.delete({ where: { id: user.id } });
@vincanger I think the idea was that you just log in with the user, using Playwright?

2024-04-04 15:26 UTC, Martinsos commented on e2e-tests/package.json
> +    "e2e:set-db-name": "chmod +x ./setupDatabaseName.sh && ./setupDatabaseName.sh",
Ah yes, because hash depends on the path to the Wasp project! That way, even if you have two Wasp projects on the disk with the same name, they will not accidentally share the database, because hash of the path on the disk to each project is used to identify that project.

2024-04-04 15:28 UTC, vincanger commented on e2e-tests/ci-start-app-and-db.js
> +};
from what I understand, the callback will not be triggered with SIGKILL, it's just abruptly terminated

2024-04-04 15:39 UTC, Martinsos commented
> i've gotten the tests to run in the same manner locally and within the CI pipeline (via playwright's `webServer` config), the only remaining issue is that the DB does not close on port 5432 and there is no way to run a callback/cleanup function to shut it down as playwright sends SIGKILL and and not SIGTERM or some other signal that would allow us to graciously stop the db.
> 
> Any suggestions @infomiho @Martinsos on how to deal with this issue? At the moment, this causes the problem that, when a user wants to start their db with `wast db start` it is already running on port 5432 after tests have run...

Ok I completely forgot that SIGKILL can't be handled! And now I learned that Playwright sends SIGKILL immediately, instead of sending SIGTERM first. And they have this issue that is describing exactly the problem we also have: https://github.com/microsoft/playwright/issues/18209 .

Seems like they are working on a fix, but nothing yet.

They do suggest using a workaround with GlobalTeardown (https://github.com/microsoft/playwright/issues/18209#issuecomment-1285645202), so maybe that is something we should investigate? I saw somebody mentioning that is too aggressive for their case, but might be good for our case?

2024-04-04 15:46 UTC, Martinsos reviewed
Left some more comments!

2024-04-05 14:12 UTC, vincanger commented on e2e-tests/playwright.config.ts
> +  webServer: process.env.CI
so martin and I tried this out, and because of DB migration issues and errors when cleaning up the DB, we decided to instruct users to start the wasp app manually before running the tests locally :)

2024-04-12 11:49 UTC, vincanger commented on e2e-tests/ci-start-app-and-db.js
> +};
in the end, we decided to let the user start the app manually before running tests locally to work around this issue

2024-04-12 11:51 UTC, vincanger commented on e2e-tests/tests/utils.ts
> +      await prisma.user.delete({ where: { id: user.id } });
in the end, we are not manipulating the db, and rather logging the user in through the app via playwright as @infomiho suggested

2024-04-12 11:52 UTC, vincanger commented on e2e-tests/package.json
> +    "e2e:start-app": "npm run e2e:wait-for-db && cd ../app && wasp db migrate-dev && wasp start",
through all the testing, this change is working great.

2024-04-12 12:45 UTC, vincanger commented on .github/workflows/e2e-tests.yml
> +          key: node-modules-${{ hashFiles('app/package-lock.json') }}
ok @Martinsos so I tried to address the caching questions by leaving the app cache in the global cache directory (~/.npm) and then putting the e2e-tests modules in a specific dir and explicitly checking for a cache hit on those before installing the necessary deps

2024-04-12 12:51 UTC, vincanger commented
okie dokie @Martinsos ready for another review. here's a rundown:

- improved caching of node modules across all projecs
- set up a local test workflow and a CI test workflow
- both workflows run Stripe CLI in the background and we log in the user and pay through stripe as part of the tests to avoid manipulating the db directly through prisma

2024-04-12 12:52 UTC, vincanger commented on app/src/server/actions.ts
> +    }
i added better error handling here in case the user forgets to add the STRIPE_PRODUCT env vars to either their app or the github action secrets

2024-04-15 10:52 UTC, Martinsos commented on e2e-tests/package.json
> +    "e2e:start-app": "npm run e2e:wait-for-db && cd ../app && wasp db migrate-dev && wasp start",
Ok, let's keep it then!

2024-04-15 14:23 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +          key: ${{ runner.os }}-wasp${{ env.WASP_VERSION }}-node${{ steps.setup-node.outputs.node-version }}-node-modules-${{ hashFiles('app/package-lock.json') }}
Ok, so seems to me like you have keys for all the right stuff!
I would still advise having `node-modules-` as a prefix, and not having it as the last thing, because it makes more sense to me to start with "what" and then the details of it, but not a biggie.

2024-04-15 14:35 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +          key: ${{ runner.os }}-wasp${{ env.WASP_VERSION }}-node${{ steps.setup-node.outputs.node-version }}-node-modules-${{ hashFiles('app/package-lock.json') }}
One thing though: let's say you add something to e2e tests, their package-lock.json changes. You didn't add anything to `app`.
What happens now, is that `.npm` will remain as it was before, but node_modules for e2e tests will change. You will save new packages to `.npm`. But will have new cache for e2e tests `node_modules`.
Maybe ok, but a bit weird. Then I would say let's cache local node_modules on both sides and that is it, not cache `.npm` for one project and local `node_modules` for another.

What I would probably go for is caching this global `.npm` instead of two local `node_modules`. What this means is having just one cache action, which is the first one you have, and then also adding `hashFiles('e2e-tests/package-lock.json')` to its key. And that is it then, you don't need the other action ("Cache E2E Tests Node Modules").

Btw you will likely want to also add
```
          restore-keys: |
            node-modules-${{ runner.os }}-
```
to that action, so that cache is not dropped on any change, but is instead just updated. I wrote this assuming you have `node-modules` as a prefix of your cache key.
This is connected to what I wrote in the other comment previously about cache behaving a bit weird regarding dropping / updating itself, I recommend digging a bit into that to understand what is happening.

2024-04-15 14:37 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +          key: node-modules-${{ hashFiles('app/package-lock.json') }}
Makes sense, still feels a bit short to me, I described though in another comment what more could be potentially done!

2024-04-16 09:42 UTC, Martinsos reviewed
Left another round of comments! We are getting close now!

2024-04-16 09:42 UTC, Martinsos commented on e2e-tests/.env
> +DATABASE_URL=postgresql://postgresWaspDevUser:postgresWaspDevPass@localhost:5432/OpenSaaS-dfca0a13c1
This is specific to the path at which project is though, right? I think I remember you gave up on this approach where it is hardcoded, maybe this is a leftover?

2024-04-16 09:42 UTC, Martinsos commented on e2e-tests/README.md
> +(TODO: Make comment on installation, setup (env vars), running, etc.)
Let's do this now?

2024-04-16 09:42 UTC, Martinsos commented on e2e-tests/package.json
> +  "scripts": {
So this is quite complicated all together, but it is all well enough named, commented on, so I think it works! It is a bit tempting to maybe spend more time on organizing it / simplifying it, but the effort would not be worth the result at this moment. So nice job!

2024-04-16 09:42 UTC, Martinsos commented on e2e-tests/playwright.config.ts
> +   */
```suggestion
  /**
   * `webServer` field tells Playwright how to run the app (webServer) it tests.
   * It seems however that there is a bug in Playwright that keeps the web server open after running tests locally https://github.com/microsoft/playwright/issues/11907,
   * causing errors when trying to run `wasp start` afterwards. To avoid this, we let Playwright run web server only in CI (where this is not a problem because after tests we don't do anything else).
   * For local development, where this does pose a nuisance, we start the app / web server manually with `wasp db start` and `wasp start` and then start tests with `npm run local:e2e:start`.
   */
```

2024-04-16 09:42 UTC, Martinsos commented on e2e-tests/playwright.config.ts
> +   */
@vincanger and please remind me, why don't we do same "manual" approach in CI? Ok, we need `npm run ci:e2e:start` because of Prisma output yeah.
But why don't we have same process, both for CI and locally, where we just run `npm run ci:e2e:start` manually, and then run tests after that? That has issues locally?

2024-04-16 09:42 UTC, Martinsos commented on e2e-tests/setupDatabaseName.sh
> +#!/bin/bash
@vincanger can you please remind me why we need this? I know we need to delete the databases that are left over running. But why do we need to set up the database name? Doesn't `wasp start db` take care of it, normally we don't have to set db name in .env?
Or this is because somebody else is connecting to the db and we need to get that name? Who?

2024-04-16 09:42 UTC, Martinsos commented on e2e-tests/setupDatabaseName.sh
> +DATABASE_URL="postgresql://postgresWaspDevUser:postgresWaspDevPass@localhost:5432/${DB_NAME}"
Right, we also assume the username and pass to match those provided by `wasp db start`.

2024-04-17 13:03 UTC, vincanger commented on .github/workflows/e2e-tests.yml
> +      - name: Cache App Node Modules
Nice. That makes more sense to me now. Thanks :)

2024-04-17 13:04 UTC, vincanger commented on .github/workflows/e2e-tests.yml
> +          path: ~/.cache/e2e-tests
yeah i was just taking a guess

2024-04-17 13:20 UTC, vincanger commented on e2e-tests/.env
> +DATABASE_URL=postgresql://postgresWaspDevUser:postgresWaspDevPass@localhost:5432/OpenSaaS-dfca0a13c1
yep. removed.

2024-04-17 13:39 UTC, vincanger commented on e2e-tests/setupDatabaseName.sh
> +#!/bin/bash
It's a leftover from earlier attempts. I've removed it now

2024-04-17 17:47 UTC, Martinsos commented on app/src/server/payments/stripeUtils.ts
> +    console.error(error.message)
Ok, if you are doing try/catch, you should certainly rethrow the error.
But now you are rethrowing it and not doing console.error -> that is really the same as not having try/catch at all! Because if onlyt thing try/catch does it retrhow an error, then it really doesn't have any effect.
But, you actually do something -> you turn it into Http 500 error. However, what Wasp server does by default, is turn any error that is not Http error into Http 500 error once it reached the top level of server (this is our default error middleware)! So there is no need for you to do this, and you can really just drop the whole try/catch modification.
Unless you want to keep console.error there, but you removed it. But I wonder why you removed it, you said you found it useful? I did wonder why since I think errors would be printed anyway, but maybe I was wrong about that?

2024-04-17 17:47 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +          key: ${{ runner.os }}-wasp${{ env.WASP_VERSION }}-node${{ steps.setup-node.outputs.node-version }}-node-modules-${{ hashFiles('app/package-lock.json') }}
Yup, exactly! It is quite convoluted, how Github cache action works, and I was confused by at the beginning, but then learned about this.

2024-04-17 18:04 UTC, Martinsos commented on e2e-tests/README.md
> +### Locally
Maybe a silly question, but when I run e2e tsts locally, what happens to the database? Local dev database is used, right? So if I was doing development locally, that same database is just used in tests? Meaning tests start with unknown state of the db + once they are done leave some data in it? How problematic is that, if that is happening?
From my experience, normally we will want to separate local dev database from the database used for e2e tests.

@infomiho your thoughts?

Ooooh and idea btw: we could expand `wasp db start` command to be like `wasp db start my-db-2` or `wasp db start my-e2e-db` -> you can give it a db name as an argument, and it will use that to be able to start a different database. So you could do `wasp db start my-dev-db` or `wasp db start my-e2e-db` and it will treat those as two separate databases. Geniussssss :D!

2024-04-17 18:04 UTC, Martinsos commented on e2e-tests/README.md
Nice README all together, coherent, to the point, and has all the important information!

2024-04-17 18:04 UTC, Martinsos commented on e2e-tests/setupDatabaseName.sh
> +#!/bin/bash
The whole setupDatabaseName.sh is a leftover? If so, sweet, because it was complex and removing it is awesome!

But, I still see the file here?

2024-04-17 18:05 UTC, Martinsos reviewed
Did another round!

2024-04-18 09:21 UTC, vincanger commented on .github/workflows/e2e-tests.yml
> +          npm run e2e:playwright:debug
ok yeah that was something i just copied over from the wasp headless tests. makes sense! I've changed it now :)

2024-04-18 09:21 UTC, vincanger commented on e2e-tests/setupDatabaseName.sh
> +#!/bin/bash
whoops. removed!

2024-04-18 09:22 UTC, vincanger commented on .github/workflows/e2e-tests.yml
> +            node-modules-${{ runner.os }}-
ok I wasn't aware of that, I thought you suggested it that way because it would match any combination of keys, but it makes sense that it is looking for a substring of that key.

2024-04-18 10:38 UTC, vincanger commented on app/src/server/payments/stripeUtils.ts
> +    console.error(error.message)
Ok interesting. What was happening was that I was getting a 500 error with a generic message. By logging it to the console I was getting a more descriptive error and was able to pinpoint what was actually the issue. I assumed by throwing the error this way, I would thus get the more descriptive error rather than the generic one.

2024-04-18 10:43 UTC, vincanger commented on app/src/server/payments/stripeUtils.ts
> +    console.error(error.message)
I tested it again and I think the reason is because the error was getting "swallowed" by the headless tests running in the CI. So, because no error was propagating up to the browser, I wasn't seeing it unless I logged it to the console with console.error.

2024-04-18 10:53 UTC, vincanger commented on e2e-tests/README.md
> +When the tests finish, you can kill the Stripe CLI process that was started by the tests:
yep, you're right. by adding `npm run local:e2e:cleanup-stripe` to the end of the local run tests script, it runs automatically when cancelling the test process with ctrl + c

2024-04-18 15:23 UTC, infomiho commented on .github/workflows/e2e-tests.yml
> +          SKIP_EMAIL_VERIFICATION_IN_DEV: true
We set this env var in `.env.server.example` as well, FYI

2024-04-18 15:29 UTC, infomiho commented on e2e-tests/README.md
> +### Locally
In Rails for example, they recognise that `test` is separate env from dev and production. By default they include a `test` env for the database which implies that there is a `test` database which is used in the tests. 

https://guides.rubyonrails.org/testing.html#the-test-database

So, the idea of having a separate `test` DB which has its own "mock data" that gets loaded for tests is a great idea! For now, with our current setup, we only recognise dev and production envs - so not good for locally running e2e tests. It's okay for the CI setup though.

2024-04-18 15:32 UTC, infomiho commented on e2e-tests/package.json
> +    "local:e2e:start-stripe": "stripe listen --forward-to localhost:3001/stripe-webhook &",
Did we mention in the README that you need to install the Stripe CLI locally to get the e2e tests working?

2024-04-18 15:33 UTC, infomiho commented
Good job 👍 

I'd maybe add a note in the README about how to install Stripe CLI locally if you want to run the e2e tests locally.

2024-04-19 08:32 UTC, vincanger commented on .github/workflows/e2e-tests.yml
> +          SKIP_EMAIL_VERIFICATION_IN_DEV: true
I will leave it there in case the user changes their local env so that CI tests don't fail

2024-04-19 08:33 UTC, vincanger commented on e2e-tests/package.json
> +    "local:e2e:start-stripe": "stripe listen --forward-to localhost:3001/stripe-webhook &",
@infomiho no we don't but I could add it, although I can't imagine someone running the tests without getting stripe working first (it's outlined in the docs)

2024-04-19 11:34 UTC, Martinsos commented on .github/workflows/e2e-tests.yml
> +            node-modules-${{ runner.os }}-
Actually it is looking for a prefix I think! So this way it matches the prefix.

2024-04-19 11:39 UTC, Martinsos commented on e2e-tests/README.md
> +### Locally
Nice @infomiho : I adde dwhat you wrote to the issue I linked above that I created for tracking this idea.

2024-04-19 11:44 UTC, Martinsos commented on .github/workflows/retag-commit.yml
> +name: Retag Commit
@vincanger you never added anything about this to some top level README, right?
I would certainly do it, as it can be quite surprising that anything that goes to `main` is basically instantly published, that should be explicitly stated.

2024-04-19 11:45 UTC, Martinsos approved these changes
@vincanger we want a long way here, but I think we are good now! Great job, we fixed a lot of stuff!

I approved but, but pls check this last comment: https://github.com/wasp-lang/open-saas/pull/69/files#r1572247170 .

Also, now that we improved stuff here, we should take that and apply the improvements on e2e tests we have in `wasp` repo. You could coordinate with @infomiho around that. I recommend doing that as soon as possible, because otherwise you will forget a lot about what we did here and it will become quite harder.

2024-04-22 08:43 UTC, merged